### ISSUE TITLE
when I print "npm init vue@next" in cmd 

### ISSUE THREAD

**Issue by zhangfanhang** [vuejs/create-vue#11]
> html:D:/myProject/fresh_homw/src/App.vue:2:23: error: Could not resolve "@/components/HelloWorld.vue" (the plugin "vite:dep-scan" didn't set a resolve directory)
    2 │ import HelloWorld from '@/components/HelloWorld.vue'

**Comment by zhangfanhang** [comment]
I didn't modify any code, just run by default

**Comment by TThz-hz** [comment]
> > html:D:/myProject/fresh_homw/src/App.vue:2:23: error: Could not resolve "@/components/HelloWorld.vue" (the plugin "vite:dep-scan" didn't set a resolve directory)
> > 2 │ import HelloWorld from '@/components/HelloWorld.vue'

这好像是路径别名的问题， 你可以修改 ``` vite.config.ts ``` 文件
```js
// import { fileURLToPath } from 'url'
import { resolve } from 'path'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), vueJsx()],
  resolve: {
    alias: {
      //  '@/': fileURLToPath(new URL('./src/', import.meta.url))
      '@': resolve(__dirname, 'src')
    }
  }
})
```

**Comment by zhangfanhang** [comment]
> > > html:D:/myProject/fresh_homw/src/App.vue:2:23: error: Could not resolve "@/components/HelloWorld.vue" (the plugin "vite:dep-scan" didn't set a resolve directory)
> > > 2 │ import HelloWorld from '@/components/HelloWorld.vue'
> 
> 这好像是路径别名的问题， 你可以修改 `vite.config.ts` 文件
> 
> ```js
> // import { fileURLToPath } from 'url'
> import { resolve } from 'path'
> 
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> import vueJsx from '@vitejs/plugin-vue-jsx'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [vue(), vueJsx()],
>   resolve: {
>     alias: {
>       //  '@/': fileURLToPath(new URL('./src/', import.meta.url))
>       '@': resolve(__dirname, 'src')
>     }
>   }
> })
> ```
