### ISSUE TITLE
Add option for bare install

### ISSUE THREAD

**Issue by danvega** [vuejs/create-vue#112]
The Vue CLI provided an option -b to exclude the scaffolded components. It would be nice if there was a way to do this with create-vue either through a flag or as one of the options.

**Comment by jd-solanki** [comment]
💯 

I regularly create projects using create-vue for reproductions or bug checking and everytime I have to:
- Remove all files from assets dir
- Remove all files from components dir
- Remove CSS import from `main.js` file
- Update `App.vue` to just simple `p` tag usage.

Yes, It will be a time saver if we have something like that we don't have to remove all these.

**Comment by ribomation** [comment]
Yes! Count me in. 👍🏻
I was scanning the sources to find out if there was a way to generate a clean project, just to find out it's currently not.

**Comment by sheptikhinv** [comment]
Agree with you, my friends

**Comment by Severino** [comment]
I was also happy to read that --bare is supported ... but in vue-cli and was not migrated to this project.

**Comment by cexbrayat** [comment]
This could definitely be an improvement.

If someone wants to open a PR, we would gladly review and merge it 👍

**Comment by runyasak** [comment]
@cexbrayat I've created a PR to add the bare configuration for this issue.
Please check at my PR: #637

@haoqunjiang If my PR overlaps with your work, please let me know, and I will make the necessary changes or updates.

**Comment by haoqunjiang** [comment]
@runyasak thanks for your effort!
But first, I think we need some consensus on the design of this feature. For instance, shall we show it in the prompts or should it be CLI-only? How "bare" is bare enough for each feature combination?
Let's discuss at https://github.com/vuejs/create-vue/pull/636
