### ISSUE TITLE
Perhaps `server.host` should be set to `true`

### ISSUE THREAD

**Issue by btea** [vuejs/create-vue#113]
After I create a project with create-vue, when I run `pnpm dev` to start the project, it will bind port `3000` by default, which is no problem.

But when I already have a project listening on port `3000`, I hope the listening port will become `3001`, but it will still listen on `3000`.

So I think `server.host` can be set to `true`.

add code here
https://github.com/vuejs/create-vue/blob/1fb74eba3bd315ff1e07649f52b4074bfed77bbe/template/base/vite.config.js#L7
```js
server: {
  host: true
}
```

**Comment by sodatea** [comment]
It's an issue that will be fixed in Vite 3. See https://github.com/vitejs/vite/pull/8543
