### ISSUE TITLE
Scaffolded project has eslint(prettier/prettier) warnings

### ISSUE THREAD

**Issue by tony19** [vuejs/create-vue#116]
### Description

There is no `.pretterrc` in the scaffold, so Prettier uses its default options, which includes [`printWidth=80`](https://prettier.io/docs/en/options.html#print-width), [`semi=true`](https://prettier.io/docs/en/options.html#semicolons), and [`singleQuote=false`](https://prettier.io/docs/en/options.html#quotes). This default config causes Prettier warnings in almost all `.vue` files.

Also, the scaffolded `.eslintrc.cjs` contains double-quoted keys, which causes Prettier warnings:

```js
/* eslint-env node */
require("@rushstack/eslint-patch/modern-module-resolution"); // 💡 Replace `"@rushstack/eslint-patch/modern-module-resolution");` with `'@rushstack/eslint-patch/modern-module-resolution')`

module.exports = {
  "root": true, // 💡 Replace `"root"` with `root`
  "extends": [
    "plugin:vue/vue3-essential",
    "eslint:recommended",
    "@vue/eslint-config-prettier"
  ] // 💡 Replace `"extends":·[⏎····"plugin:vue/vue3-essential",⏎····"eslint:recommended",⏎····"@vue/eslint-config-prettier"⏎··` with `extends:·['plugin:vue/vue3-essential',·'eslint:recommended',·'@vue/eslint-config-prettier'`
}
```

I think that's caused by `JSON.stringify()` in the following line:

https://github.com/vuejs/create-vue/blob/58c4fdb5c53a5019401a86568868ce9cf255a3ce/utils/renderEslint.ts#L65

### Steps to reproduce

1. Scaffold a project with `create-vue`:

    ```sh
    npm init vue my-project # select ESLint and Prettier options
    ```

2. Open the project in VS Code.

3. In VS Code, install the official [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) (if not already).

5. Observe the linter warnings in all `.vue` files, and in `.eslintrc.cjs`.

### Workaround

Copy `create-vue`'s [`.prettierrc`](https://github.com/vuejs/create-vue/blob/afddba9/.prettierrc) (which I presume was used to format the templates here) to the scaffolded project's root directory, but I think that should be done by `create-vue` automatically.

**Comment by cexbrayat** [comment]
I tested locally with create-vue v3.8 and I see the generated `.prettierrc.json` file.

```
❯ npm create vue@3.8.0 --yes

Vue.js - The Progressive JavaScript Framework

✔ Nom du projet : … prettier
✔ Ajouter TypeScript ? … Non / Oui
✔ Ajouter le support de JSX ? … Non / Oui
✔ Ajouter Vue Router pour le développement d'applications _single page_ ? … Non / Oui
✔ Ajouter Pinia pour la gestion de l'état ? … Non / Oui
✔ Ajouter Vitest pour les tests unitaires ? … Non / Oui
✔ Ajouter une solution de test de bout en bout (e2e) ? › Non
✔ Ajouter ESLint pour la qualité du code ? … Non / Oui
✔ Ajouter Prettier pour le formatage du code ? … Non / Oui

Génération du projet dans /Users/cedric/Code/temp/prettier...

Terminé. Exécutez maintenant :

  cd prettier
  npm install
  npm run format
  npm run dev
```

```
drwxr-xr-x  12 cedric  staff   384 10 nov 14:28 .
drwxr-xr-x  52 cedric  staff  1664 10 nov 14:28 ..
-rw-r--r--   1 cedric  staff   296 10 nov 14:28 .eslintrc.cjs
-rw-r--r--   1 cedric  staff   302 10 nov 14:28 .gitignore
-rw-r--r--   1 cedric  staff   163 10 nov 14:28 .prettierrc.json
drwxr-xr-x   3 cedric  staff    96 10 nov 14:28 .vscode
-rw-r--r--   1 cedric  staff   701 10 nov 14:28 README.md
-rw-r--r--   1 cedric  staff   331 10 nov 14:28 index.html
-rw-r--r--   1 cedric  staff   590 10 nov 14:28 package.json
drwxr-xr-x   3 cedric  staff    96 10 nov 14:28 public
drwxr-xr-x   6 cedric  staff   192 10 nov 14:28 src
-rw-r--r--   1 cedric  staff   309 10 nov 14:28 vite.config.js
```

And running `yarn lint --no-fix` doesn't yield any warnings:
```
yarn lint --no-fix
yarn run v1.22.19
$ eslint . --ext .vue,.js,.jsx,.cjs,.mjs --fix --ignore-path .gitignore --no-fix
✨  Done in 1.01s.
```

So this issue has probably been fixed since you opened it @tony19 ?

I'll close it, feel free to ping me if you come across a scenario where this doesn't work (providing a repro would be great in that case!)
