### ISSUE TITLE
Add V2.7 to the vue2 template

### ISSUE THREAD

**Issue by yanbowe** [vuejs/create-vue#118]
Add V2.7 to the vue2 template

**Comment by sodatea** [comment]
Added. it's released as a beta currently because JSX isn't supported yet and I haven't updated Cypress to v10.
I've also added aliases for it. You can try it out by executing `npm init vue@naruto`.

**Comment by yanbowe** [comment]
> Added. it's released as a beta currently because JSX isn't supported yet and I haven't updated Cypress to v10.
> I've also added aliases for it. You can try it out by executing `npm init vue@naruto`.

thanks
