### ISSUE TITLE
vue@2  should upgrade to vue 2.7 and @vitejs/plugin-vue2

### ISSUE THREAD

**Issue by fyeeme** [vuejs/create-vue#119]
as vue 2.7  has the ability to support composition api. this repo should upgrade `npm init vue@2` to vue 2.7 and @vitejs/plugin-vue2

**Comment by JosueNicholson** [comment]
I'm trying to create a new vue 2.7 project using vite build tool. Does someone can enlight me about how steps should I take, please? I have already tried to create with `npm init vue@2` command, and then upgrade vue 2.6.14 to 2.7.0 but got no success.

**Comment by fyeeme** [comment]
@JosueNicholson  here is to repo for using vite and vue 2.7 , the latter is intergrated with ts

[https://github.com/fyeeme/vite-vue2.7](https://github.com/fyeeme/vite-vue2.7)

[https://github.com/fyeeme/vite-vue2.7-ts](https://github.com/fyeeme/vite-vue2.7-ts)

**Comment by xfq** [comment]
Currently, you can use `npm init vue@naruto` as a workaround.

**Comment by JosueNicholson** [comment]
@xfq Thank you very much!

**Comment by sodatea** [comment]
Shipped in v2.1.0.
Now you can use either `npm init vue@2` or `npm init vue@naruto` to create a Vue 2 project.

The project templates have now been synced with Vue 3's.

**Comment by Jurool** [comment]
@sodatea 
I have a question, the projects created with npm init vue@2 or npm init vue@naruto are all vue3, not vue2, why? I tried both locally and stackblitz, same result.
![image](https://user-images.githubusercontent.com/26647750/185055717-e8e50f9b-2e22-4df2-a659-b38436329dd2.png)

**Comment by sodatea** [comment]
StackBlitz is not a real shell environment, so that's expected. They might not have implemented the feature to read the version number in the `npm init` command.

But I can't reproduce your issue locally. `npm init vue@2` creates a Vue 2 project on my machine.
