### ISSUE TITLE
使用TypeScript时似乎缺少 “@types/node” 依赖，以及路径别名问题

### ISSUE THREAD

**Issue by TThz-hz** [vuejs/create-vue#12]
# 使用TypeScript时似乎缺少 “@types/node” 依赖
# 路径别名配置似乎也有问题
```zsh
 > html:src/App.vue:5:7: error: Could not resolve "@/components/HelloWorld.vue" (the plugin "vite:dep-scan" didn't set a resolve directory)
    5 │ import '@/components/HelloWorld.vue'
      ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > html:/src/views/HomeView.vue:5:7: error: Could not resolve "@/components/TheWelcome.vue" (the plugin "vite:dep-scan" didn't set a resolve directory)
    5 │ import '@/components/TheWelcome.vue'
      ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```js
// import { fileURLToPath } from 'url'
import { resolve } from 'path'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), vueJsx()],
  resolve: {
    alias: {
      //  '@/': fileURLToPath(new URL('./src/', import.meta.url))
      '@': resolve(__dirname, 'src')
    }
  }
})

```

**Comment by zhanglolo** [comment]
不应该是`import HelloWorld from '@/components/HelloWorld.vue'`，为什么你这里直接import组件

**Comment by TThz-hz** [comment]
> 不应该是`import HelloWorld from '@/components/HelloWorld.vue'`，为什么你这里直接import组件

没有直接import组件。项目创建完成后没有改动代码, 我粘贴的是控制台打印的错误
将 vite.config.ts 文件中的  ` '@/': fileURLToPath(new URL('./src/', import.meta.url))` 
改为  ` '@': fileURLToPath(new URL('./src/', import.meta.url))` 就行了，难道是因为Windows系统的问题？

**Comment by zhanglolo** [comment]
> > 不应该是`import HelloWorld from '@/components/HelloWorld.vue'`，为什么你这里直接import组件
> 
> 没有直接import组件。项目创建完成后没有改动代码, 我粘贴的是控制台打印的错误 将 vite.config.ts 文件中的 ` '@/': fileURLToPath(new URL('./src/', import.meta.url))` 改为 ` '@': fileURLToPath(new URL('./src/', import.meta.url))` 就行了，难道是因为Windows系统的问题？

Mac os 上正常。

**Comment by sodatea** [comment]
似乎是 `/` 引起的。
Vite 2 之后 alias 不需要加 `/`，我给忘了。

**Comment by TThz-hz** [comment]
> 似乎是 `/` 引起的。 Vite 2 之后 alias 不需要加 `/`，我给忘了。

另外使用TypeScript时，这个是不是缺少 “@types/node” 依赖
![image](https://user-images.githubusercontent.com/56644784/143443163-0bd88f5f-1bfd-46e1-b8e8-b1d178efc63b.png)

**Comment by sodatea** [comment]
是的……感谢指出

**Comment by zhanglolo** [comment]
```javascript
export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      // "@": fileURLToPath(new URL("./src", import.meta.url)), 
      // "@/": fileURLToPath(new URL("./src", import.meta.url)), //error
      // "@": fileURLToPath(new URL("./src/", import.meta.url)),
      // '@/': fileURLToPath(new URL('./src/', import.meta.url))
    },
  },
});
```

测试了这四种情况，只有第二种会报错。
@TThz-hz 你的错误能像这样再次还原吗。

**Comment by TThz-hz** [comment]
> 

看一下最近的 commit，已经修复了
```js
      // "@": fileURLToPath(new URL("./src", import.meta.url)), 
      // "@/": fileURLToPath(new URL("./src", import.meta.url)),  //error
      // "@": fileURLToPath(new URL("./src/", import.meta.url)),
      // '@/': fileURLToPath(new URL('./src/', import.meta.url))   //error
```

**Comment by zhanglolo** [comment]
> 看一下最近的 commit，已经修复了
> 
> ```js
>       // "@": fileURLToPath(new URL("./src", import.meta.url)), 
>       // "@/": fileURLToPath(new URL("./src", import.meta.url)),  //error
>       // "@": fileURLToPath(new URL("./src/", import.meta.url)),
>       // '@/': fileURLToPath(new URL('./src/', import.meta.url))   //error
> ```

有点奇怪，我本地第四种是正常进入的，组件也都能加载。

**Comment by TThz-hz** [comment]
> ```js
> '@/': fileURLToPath(new URL('./src/', import.meta.url))
> ```

Windows系统
![image](https://user-images.githubusercontent.com/56644784/143446905-da2639fa-fd22-4bd7-9949-a49b099639a4.png)

**Comment by zhanglolo** [comment]
😂 Mac OS, 看样子还和系统有关？

<img width="725" alt="截屏2021-11-25 21 10 05" src="https://user-images.githubusercontent.com/27875371/143447481-16c5a511-333f-4cd5-9884-6f7893294233.png">
