### ISSUE TITLE
node types causing `setTimeout` wrong return type 

### ISSUE THREAD

**Issue by troy351** [vuejs/create-vue#122]
- Create vue 2 project using following config
![QQ截图20220715152725](https://user-images.githubusercontent.com/8372385/179177297-0fd08d5f-523b-4932-825b-b97aa82221b0.png)

- `npm install`
- open `main.ts` and write down `const timer = setTimeout(() => {})`

See the type of timer is `Timeout` which is from `@types/node`, it should be `number`
![QQ截图20220715154936](https://user-images.githubusercontent.com/8372385/179177804-afeac30d-2bcc-44ca-b9e4-ea692452dd02.png)

**Comment by sodatea** [comment]
Can't reproduce.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/3277634/179181170-40e5e234-f9a1-41fd-ab1f-16cdcee25f8e.png">

The `tsconfig.json` for `src/main.ts` is extended from `@vue/tsconfig/tsconfig.web.json`, which explicitly resets the types.  It won't include the type from `@types/node`

https://github.com/vuejs/tsconfig/blob/26fc528db347dbbbbaa2ea15d3c2d95c197887b7/tsconfig.web.json#L17
https://www.typescriptlang.org/tsconfig#types
