### ISSUE TITLE
Question: Are there plans to upgrade to Vite 3?

### ISSUE THREAD

**Issue by brandonleichty** [vuejs/create-vue#124]
With the exciting announcement of Vite 3, I was wondering if there are plan to upgrade this tool to v3 soon?

**Comment by sodatea** [comment]
It was blocked on a small regression that affected Vite + Cypress Component Testing.

Fixed and released now.

**Comment by coure2011** [comment]
@sodatea 
Its fixed only for `npm init vue@3`.

Will it not be applied for vue@2?
