### ISSUE TITLE
vite3.0 node:url

### ISSUE THREAD

**Issue by Rain20199** [vuejs/create-vue#140]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/56431955/183798093-fda5fd99-60aa-49e5-94d2-4ca77f289deb.png">

**Comment by xfq** [comment]
What version of Node.js are you using?

**Comment by sodatea** [comment]
https://github.com/vitejs/vite/blob/6d952252c7a3b92b2f82a7c78c230e0a152fd2a6/packages/vite/package.json#L34-L36
Vite 3 only supports Node.js `"^14.18.0 || >=16.0.0"`
https://nodejs.org/api/esm.html#node-imports
`node:` imports were added in: v14.13.1, v12.20.0
