### ISSUE TITLE
after execute  npm init vue@2  & npm run build error

### ISSUE THREAD

**Issue by mahaoming** [vuejs/create-vue#141]
![image](https://user-images.githubusercontent.com/31064550/184163409-04728bec-4d10-470b-863b-efef8b845af2.png)
![image](https://user-images.githubusercontent.com/31064550/184163508-192d7c16-98ed-4603-9655-4793049f97f1.png)

![image](https://user-images.githubusercontent.com/31064550/184163630-957db158-4bea-494a-8a4e-27200b057aac.png)
may be not support ie11 ?

**Comment by mahaoming** [comment]
after init a project, run npm run build error

**Comment by sodatea** [comment]
Let's track it at https://github.com/vuejs/create-vue/issues/141

For now, you can use [`pnpm.overrides`](https://pnpm.io/package_json#pnpmoverrides) to pin the `systemjs` dependency version to `6.12.1`

**Comment by sodatea** [comment]
Let's track it at https://github.com/vitejs/vite/issues/9618

For now, you can use [`pnpm.overrides`](https://pnpm.io/package_json#pnpmoverrides) to pin the `systemjs` dependency version to `6.12.1`

**Comment by sodatea** [comment]
Fixed in `@vitejs/plugin-legacy@2.0.1`
