### ISSUE TITLE
prettier not working after scaffold

### ISSUE THREAD

**Issue by jmarshall9120** [vuejs/create-vue#143]
After scaffolding a project with create-vue prettier initializes in a broken state:

```
// prettier console output
["INFO" - 12:37:31 PM] Formatting file:///m%3A/source/bandz-padline-interface-vite/vite.config.js
["ERROR" - 12:37:31 PM] Invalid prettier configuration file detected.
["ERROR" - 12:37:31 PM] ENOENT: no such file or directory, open 'm:\source\bandz-padline-interface-vite\.prettierrc.json'
Error: ENOENT: no such file or directory, open 'm:\source\bandz-padline-interface-vite\.prettierrc.json'
["ERROR" - 12:37:31 PM] Invalid prettier configuration file detected. See log for details.
```

Maybe the fix here is just scaffold a basic prettierrc.json when creating the project?

**Comment by LinusBorg** [comment]
Are you saying these are loss from some kinda of prettier Editor extension?

And this happens because there's is no coughing found? Then that's not related to create-vue

The Basic scaffold does not include prettier support so it would not make sense for most users to have this config file included.

If that's not what you are referring to, please explain

**Comment by jmarshall9120** [comment]
Here's me running the scaffold:

![image](https://user-images.githubusercontent.com/30184747/185765230-f519a9bd-5102-47d0-87a1-f56bcc287908.png)

You can decide what the parameters of responsibility for your project are, but since I'm prompted with this option it feels to me, as a user, it should work out of the box.  

I am using VS code, and it does contain a prettier extension - "Prettier - Code formatter".  However, that extension just seems to following the rules.

This is the recommended steps from prettier for installation on [their site](https://prettier.io/docs/en/install.html)
![image](https://user-images.githubusercontent.com/30184747/185765435-4084705c-5f23-475f-8d8c-f39f6d7663af.png)

Also you could just not care about IDE support, but it is a popular one and it would be fairly simple to ship a basic prettier configuration like:

```
//.prettierrc.json
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "endOfLine": "auto"
}
```

To me it feels in the scope of what I would expect when you prompt to include prettier at scaffold time.

**Comment by LinusBorg** [comment]
Thanks for clarifying how you created your project with prettier explicitly selected, that was not clear from your original description.

I personally never missed the file as I a) don't use the prettier extension (I let eslint run it) and b) always copy my own preferred config into new projects anyway. so I was not aware that a missing file would lead to the extension not working even if prettier is installed.

Now that I get the full picture, I agree adding this file likely makes sense.

**Comment by sodatea** [comment]
Can't reproduce. On my machine the log is:
```
["INFO" - 3:31:05 PM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
```

Prettier should work without a configuration file.

Does the error disappear after you add a `.prettierrc.json`?

**Comment by sodatea** [comment]
From the screenshot and the error messages, I can guess 2 possible causes:
1. The uppercase `M` (in the shell prompt, where the project is created) and lower case `m` (the extension's error log, I suspect it's where the VS Code is launched) in the path, if used with a case-sensitive tool, could be problematic.
2. The uncommon drive letter `M`, is your project on a network drive or a virtual drive? If so, some tools may not support that well.

**Comment by sodatea** [comment]
Anyway, an empty `.prettierrc.json` sounds a good idea. I'll add it in the next versions.
But I highly doubt that could fix this issue.

**Comment by jmarshall9120** [comment]
@sodatea 
Adding the .prettierrc.json did in fact fix my issue.  Here is my environment info:
* Windows 11
* VSCode 1.70.2
* Prettier - Code formatter v9.8.0

The letter `M` for my drive, comes from windows 11 auto install new memory setup.  It is a second stick of memory in the expansion PCI port for my drive.  Unless I'm mistaken, drive letters should not break applications unless people are hardcoding paths. 

Let me know if I missed something.  

I think including the .prettierrc.json config file is a great idea!!!
