### ISSUE TITLE
Scaffolded project came with TypeScript errors

### ISSUE THREAD

**Issue by ZackPlauche** [vuejs/create-vue#145]
**NOTE**: Everything still runs when I use `yarn dev`.

Running:
Windows 11 (latest update as of time posted)
VSCode (latest version as of time posted)

I don't have any custom basic / fancy TypeScript configuration in my VSCode. Settings are defaults.

How I initialized it:
![image](https://user-images.githubusercontent.com/43456955/185948882-1536a2d3-90cd-4d37-853b-49c16b875152.png)

Error 1:
![image](https://user-images.githubusercontent.com/43456955/185949069-8bf11149-ac25-44d0-98e5-1b76f618edd0.png)

Error 2: 
![image](https://user-images.githubusercontent.com/43456955/185949156-805f4a31-5570-4d52-a57e-b9e6e9fd80d8.png)

Error 3: 
![image](https://user-images.githubusercontent.com/43456955/185949797-c6ca789f-c20f-4f5e-9188-11da9e6b508c.png)

Error 4: 
![image](https://user-images.githubusercontent.com/43456955/185949290-674ea9c3-a889-4718-a673-67a902e45628.png)

Error 5: 
![image](https://user-images.githubusercontent.com/43456955/185949450-ff9a2820-815d-46be-87c5-c75348e07ec8.png)

Error 6:
![image](https://user-images.githubusercontent.com/43456955/185949526-3385fe61-a18f-49c4-b1ea-a197a76e5c6b.png)

Error 7:
![image](https://user-images.githubusercontent.com/43456955/185949986-de132857-07c2-406f-9f99-1983f26e7b30.png)

Error 8: 
![image](https://user-images.githubusercontent.com/43456955/185950288-3dfa1429-016c-4568-8624-0e985b65d602.png)

Error 9:
![image](https://user-images.githubusercontent.com/43456955/185950476-f31d129c-5d49-476e-a42b-d84f968373ba.png)

**Comment by sodatea** [comment]
Can't reproduce.

Seems the dependencies aren't correctly installed?
Most of the issues should be fixed if `@vue/tsconfig`

The errors on `.vue` files, though, would be fixed if you install the Volar and TypeScript Vue Plugin (Volar) extensions as recommended in the generated README.

**Comment by ZackPlauche** [comment]
@sodatea Installing the TypeScript Vue Plugin (Volar) fixed everything. Thanks!
