### ISSUE TITLE
Cypress: add import of base.css for every component spec file

### ISSUE THREAD

**Issue by nicosemp** [vuejs/create-vue#15]
### Steps to reproduce:

- Create a new project with Cypress > yes

### Problem: 
Currently the App.vue file is created with a global style tag (not scoped) that imports a base.css style. This is perfectly fine as it's intended to be available throughout the app.
```css
@import '@/assets/base.css';
```
When we try to run `npm run test:unit` Cypress doesn't import the base.css automatically. So the HelloWorld.spec.ts file executes correctly without failing, but the style from main.css is missing.

This can be easily fixed with a simple `import "@/assets/base.css";` inside the spec file, but having to import it in every component spec file is inefficient.
One could use that same line inside the `cypress/support/index.ts` file: this runs before each spec, so they can all use the global css. But this breaks `npm run test:e2e` as integration tests will not be able to resolve the path.

What's the best way to import a stylesheet in every component spec file?
A best practice should be defined, and added to the default template for new projects, when the user chooses to include Cypress.

**Comment by sodatea** [comment]
Fixed in 3.2.3

https://github.com/vuejs/create-vue/commit/732547cebf8f8489d0355c088bbdbf78cb1b781c
https://github.com/vuejs/create-vue/commit/f432a7ab13ade177e7c0a0a7f50f17b6370b46ca
https://github.com/vuejs/create-vue/commit/64902ba6631689563cbc36b62f2b0b52546380bf
