### ISSUE TITLE
Adding cypress breaks type checking

### ISSUE THREAD

**Issue by groundfloorwebb** [vuejs/create-vue#152]
First off, thanks for including a typescript/cypress option, having suffered through configuring this in Vue 2 it's very much appreciated.

I'm in the process of shifting our toolchain from Vue 2 to 3 and I'm prototyping a starter project that matches our current setup. Critically this means Vite, Typescript, Eslint and Cypress. Everything works great until I add cypress to my options, as soon as I do running `npm run type-check` stops reporting type errors. I'm running node v18.7.0.

To reproduce
1. `npm init vue@3`
2. Select typescript and cypress.
3. Add a simple type error like `const foo: boolean = 'bar';` to `src/main.ts`.
4. `npm run type-check`
5. No errors reported.

Running the same test but omitting the cypress option will produce errors.

**Comment by sodatea** [comment]
It’s similar to https://github.com/vuejs/create-vue/pull/107
Please edit the `type-check` command to `vue-tsc --noEmit -p tsconfig.cypress-ct.json --composite false`.

**Comment by groundfloorwebb** [comment]
Thanks for the answer @sodatea , I can confirm that the fix does work. I ended up going with `vue-tsc --noEmit -p tsconfig.app.json --composite false && vue-tsc --noEmit -p tsconfig.cypress-ct.json --composite false`, the script above only checks the cypress code while this tests both. There might be a more elegant solution, but this does the job.

I would say that this bug is distinct from #100 , the two are adjacent but I don't think they're actually related. I would recommend altering the type-check command generated by this combination of options so it type-checks correctly from the start.
