### ISSUE TITLE
--ts feature flag ignored

### ISSUE THREAD

**Issue by khusseini** [vuejs/create-vue#153]
Hello there,

I am trying in a script to enforce the creationg of a vue project with Typescript.
I am running the `npm init` like so:

```bash
npm init vue@3 my-project --ts
```

For some reason I am still being asked if I want to use typescript and it is preselected with `No`.

What am I doing wrong?

**Comment by sodatea** [comment]
https://docs.npmjs.com/cli/v8/commands/npm-init#forwarding-additional-options
https://docs.npmjs.com/cli/v8/commands/npm-exec#npx-vs-npm-exec

> a double-hyphen `--` flag can be used to suppress npm's parsing of switches and options that should be sent to the executed command

So when using `npm init`, the flags should be preceded by a `--`, that is:
```
npm init vue@3 my-project -- --ts
```
