### ISSUE TITLE
regression: eslint-cypress-plugin is missing in v3.3.3

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/create-vue#155]
It looks like f4ac339764ebd06bd23705bbaabb14fa229c31a6 introduced some regressions by using https://github.com/vuejs/create-eslint-config:

- `eslint-plugin-cypress` is no longer included in the project dependencies, making the `lint` task fail right away in a new project
- an empty JSON file `.prettierrc.json` is generated, alongside the existing `.prettierrc` config.

See https://github.com/cexbrayat/create-vue-diff/compare/3.3.2...3.3.3 for the differences

**Comment by sodatea** [comment]
> * `eslint-plugin-cypress` is no longer included in the project dependencies, making the `lint` task fail right away in a new project

🤦‍♂️ It was due to a typo. I really should have written proper tests before refactoring.

> * an empty JSON file `.prettierrc.json` is generated, alongside the existing `.prettierrc` config.

Can you elaborate? I don't think there were any `.prettierrc`s generated in the previous versions.

**Comment by cexbrayat** [comment]
No my mistake, you're right there are no prettier config at the moment. I just thought it was weird to have an empty JSON 👍

**Comment by sodatea** [comment]
It's recommended in the prettier documentation:

> Then, create an empty config file to let editors and other tools know you are using Prettier:

https://prettier.io/docs/en/install.html

**Comment by sodatea** [comment]
Fixed in 3.3.4
