### ISSUE TITLE
ESLint error in initial project on emit

### ISSUE THREAD

**Issue by miroljub1995** [vuejs/create-vue#160]
When adding simple emit to `HelloWorld.vue` I get lint error.

Example:
![image](https://user-images.githubusercontent.com/46632388/189100946-6fd171c0-014b-4115-87b7-7f111f6e9ce7.png)

Do we need to take some extra step to setup lint properly, but without turning off this rule for whole project?

**Comment by miroljub1995** [comment]
Looks like it is linked to this PR https://github.com/vuejs/eslint-config-typescript/pull/47

**Comment by sodatea** [comment]
Fixed in `@vue/eslint-config-typescript` v11.0.2
