### ISSUE TITLE
eslint/prettier rules conflict

### ISSUE THREAD

**Issue by ihardz** [vuejs/create-vue#165]
### Vue version

3.2.39

### Link to minimal reproduction

https://github.com/ihardz/vue3-eslint-prettier-rules-conflict

### Steps to reproduce

1. `npm init vue@latest`
2. Setup:
```
√ Project name: ... test-app
√ Add TypeScript? ... No / Yes -> Yes
√ Add JSX Support? ... No / Yes -> No
√ Add Vue Router for Single Page Application development? ... No / Yes -> Yes
√ Add Pinia for state management? ... No / Yes -> No
√ Add Vitest for Unit Testing? ... No / Yes -> No
√ Add Cypress for both Unit and End-to-End testing? ... No / Yes -> No
√ Add ESLint for code quality? ... No / Yes -> Yes
√ Add Prettier for code formatting? ... No / Yes -> Yes
```
3. `cd test-app`
4. update _.prettierrc.json_ with following:
```
{
  "singleQuote": true
}
```
5. open _src/App.vue_ (for example)
6. format document with Prettier

### What is expected?

There are no warnings in VSCode

### What is actually happening?

warnings in VSCode:
![image](https://user-images.githubusercontent.com/31627738/191220006-1520b282-8989-469c-9ba0-995d599d0b39.png)

**Comment by LinusBorg** [comment]
can't reproduce this, works fine in my IDE. does the problem only happen in vue files? I recall the old Vetur extension did include a default eslint config, and it might not detect the `.eslintrc.cjs` due to the rather recent `cjs` extension.

**Comment by LinusBorg** [comment]
I followed your instructions and only found that when formatting `App.vue` with Volar, it did format the template in a a way that prettier did not like - which is expected, the two format differently.

I do not get any eslint warnings after formatting `App.vue` with prettier. And yes, eslint is working in VSCode otherwise, i.e. for unused variables etc).

**Comment by xfq** [comment]
I can't see the warning either. I've tried:

```
* VS Code 1.71.2
* esbenp.prettier-vscode 9.9.0
* Vue.volar 0.40.13
```
