### ISSUE TITLE
Replace `minimist` with `@pkgjs/parseargs`

### ISSUE THREAD

**Issue by sodatea** [vuejs/create-vue#168]
https://github.com/substack/minimist now returns 404
https://twitter.com/dan_abramov/status/1573715996573155336
Likely because @substack didn't wanna use 2FA.

Anyway, Node.js provides a built-in `util.parseArgs` helper since v18.3.0, which uses https://github.com/pkgjs/parseargs underlylingly. The package supports Node.js >= 14. We should use it instead.

**Comment by broql** [comment]
Is this issue still valid? Can I take it?

**Comment by sodatea** [comment]
Yeah, go ahead please.
