### ISSUE TITLE
Missing PWA scafolding? 

### ISSUE THREAD

**Issue by tvld** [vuejs/create-vue#170]
Previously we would see an option to enable Progressive Web Apps. Is this ``create-vue`` still the way to do it?

**Comment by LinusBorg** [comment]
We will likely keep the scope of OOTB scaffoling smaller than we did in Vue CLI for maintenance reasons.

You can add PWA support with this Vite plugin by antfu: https://vite-plugin-pwa.netlify.app/

**Comment by tvld** [comment]
Super thank you. It's good to have the issue here for further reference ;-)))
