### ISSUE TITLE
Possible Cypress related issue with package.json scripts setup

### ISSUE THREAD

**Issue by cfjedimaster** [vuejs/create-vue#175]
I scaffolded a new application with `npm init vue@latest`, and during the prompts, I selected YES to Cypress. After it was done, I went into the directory, ran `npm i`, and then tried:

    npm run test:e2e

When I did, it hung at:

![image](https://user-images.githubusercontent.com/393660/195388844-57820019-a0bd-4293-9b96-0b09affee31d.png)

I asked around on the Cypress discord, and did some digging, and noticed the following.

If I did `npm run dev`, of course the Vue app worked fine.   But if I ran the `preview` task as created during scaffolding, `vite preview --port 4173`, it did NOT build the Vue app. I'd hit the URL and get, "Cannot GET /" (or something like that ;). 

If I remove 'preview' from the command:

        "preview": "vite --port 4173",

I can then run the `test:e2e` task ok. 

So there's definitely a workaround, but "out of the box", it seems like the scaffolded scripts may be wrong?

**Comment by sodatea** [comment]
https://github.com/vuejs/create-vue-templates/tree/v3.3.4/cypress#run-end-to-end-tests-with-cypress

The generated README has explicitly stated that `build` should be run before `test:e2e`
