### ISSUE TITLE
Contrast issue with background colour

### ISSUE THREAD

**Issue by ajmas** [vuejs/create-vue#193]
I just tried running on my Mac, using macOS 12.5.1:

```
# not sure if the was necesary
npm install create-vue -g

npm create vue@3  
```

and the choice of colours for the output make it really hard to read:

<img width="779" alt="Screenshot 2022-11-10 at 13 41 59" src="https://user-images.githubusercontent.com/682269/201179739-e7f686b1-d0eb-45ed-addb-9209f44f730b.png">

My terminal theme is green/black, old school VT100 style.

**Comment by LeonSolisPedro** [comment]
I have the same problem, my terminal is on default settings and I'm running macOS Ventura.


The way this issue hasn't receive any reply, shows how slow is the adoption of this, and Vue 3 is in general.
