### ISSUE TITLE
Init or Create?

### ISSUE THREAD

**Issue by ajmas** [vuejs/create-vue#194]
There seems to be a conflict between the instructions and the screenshot in the README. Should it be init or create, or either?

<img width="852" alt="image" src="https://user-images.githubusercontent.com/682269/201180911-8cb9de28-50b7-44c6-b59a-7e1d9e83f3cd.png">

**Comment by btea** [comment]
init and create seem to be equivalent, [docs](https://docs.npmjs.com/cli/v9/commands/npm-init)

**Comment by ajmas** [comment]
Fair enough, though would be want the screenshot and instructions to be consistent? If it is not a concern, then I’ll close this issue
