### ISSUE TITLE
Setting vitest environment in `package.json` doesn't play well with VS Code's vitest extension

### ISSUE THREAD

**Issue by segevfiner** [vuejs/create-vue#199]
Setting the vitest environment to jsdom in the `package.json` instead of in `vite.config.ts` doesn't play well with the VS Code vitest extension which won't know about it and will fail to run vitest without further configuration.

https://github.com/vuejs/create-vue/blob/99775d344f7cfd82d8890d6bbc942c911e6021e7/template/config/vitest/package.json#L3

**Comment by sodatea** [comment]
I think this needs to be reported to the Vitest VS Code extension instead of here?

It is a fair use of the CLI arguments considering how few options the command needs to use. The VS Code extension should support this use case.

**Comment by segevfiner** [comment]
How would it know which script it should look at? There is probably a VS Code setting to set which CLI arguments should be used, but that's not as good as it just working without further configuration.

**Comment by sodatea** [comment]
I think they can use some heuristics to suggest a setting.

But yeah, your argument makes sense. It is not ideal.
I need to figure out a way to make it work out of the box without sacrificing simplicity.

**Comment by segevfiner** [comment]
Isn't just setting it in `vite.config.ts` simple enough?

**Comment by sodatea** [comment]
I kinda don't like using `/// <reference types="vitest" />`, so I'm looking into the documentation, trying to find a different way now. If there turn out to be no better options, I'll use it then.

**Comment by segevfiner** [comment]
BTW, Seems like this had another unfortunate side effect, vitest in VS Code didn't know about the root flag so it would also pick up playwright tests.

**Comment by sodatea** [comment]
Yeah, the `--root src/` argument was initially introduced to work around that problem.

Anyway, thanks to @beta, now we'll create a perfectly working and scalable `vitest.config.js` file for new projects: https://github.com/vuejs/create-vue/pull/227/files
