### ISSUE TITLE
yarn installation process gives warnings

### ISSUE THREAD

**Issue by kajojify** [vuejs/create-vue#213]
Hello! 

I decided to create a new Vue project with help of `create-vue` and `yarn` tools. I ran `yarn create vue@latest` then set the following options:
✔ Project name: … vue-project
✔ Add TypeScript? … Yes
✔ Add JSX Support? … Yes
✔ Add Vue Router for Single Page Application development? … Yes
✔ Add Pinia for state management? … Yes
✔ Add Vitest for Unit Testing? … No
✔ Add an End-to-End Testing Solution? › No
✔ Add ESLint for code quality? … Yes
✔ Add Prettier for code formatting? … Yes

Then I went to `vue-project` folder, ran `yarn` command and saw this:
![image](https://user-images.githubusercontent.com/20267977/207309377-7b5bbfc3-27ef-4a97-b41e-a2c1ffbc119c.png)

Is there anything I can do to quickly fix this? 
Thank you.

**Comment by sodatea** [comment]
I think these warnings can be safely ignored. They are mere warnings, after all.

If you are interested in more details:
- The `soucemap-codec` warning: tracked at https://github.com/vuejs/core/issues/7329
- The `fsevents` warning: possibly a bug of the npm registry, explained at https://github.com/yarnpkg/yarn/issues/8052#issuecomment-735764698 and a discussion is opened at https://github.com/npm/feedback/discussions/804
- The `@npmcli/move-file` warning: tracked at https://github.com/nodejs/node-gyp/issues/2756
- The `@vue/babel-plugin-jsx` warning: I can fix it tomorrow.

**Comment by kajojify** [comment]
Hello. Thank you!

**Comment by TwT-L** [comment]
I get an error, When I run the `yarn create vue@latest` command.
```bash
yarn create v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "create-umi > sylvanas > @umijs/fabric > eslint-plugin-compat@3.6.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning "create-umi > sylvanas > @umijs/fabric > eslint-plugin-jsx-a11y@6.2.3" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6".
[4/4] 🔨  Building fresh packages...
success Installed "create-vue@3.7.5" with binaries:
      - create-vue
/bin/sh: /usr/local/bin/create-vue@latest: No such file or directory
error Command failed.
Exit code: 127
Command: /usr/local/bin/create-vue@latest
Arguments:
Directory: /Users/lichin/Documents/code/test
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by sodatea** [comment]
Yarn v1 doesn't support appending `@tag` to the `create` command. So just use `yarn create`.

**Comment by tomatobybike** [comment]
> Yarn v1 不支持附加`@tag`到`create`命令。所以只需使用`yarn create`.

Good ！！

**Comment by yangmingshan** [comment]
> @jamesdongdong Latest yarn version is 4.1.1-dev, and it supports appending `@tag`. You can reference it here - https://yarnpkg.com/cli/add I don't think Vue doc needs to be updated.

But Yarn v4 does not support the `yarn create` command, you should use [yarn dlx](https://yarnpkg.com/cli/dlx), so `yarn create vue@latest` is a wrong command anyway.

Should we update the documentation?

**Comment by Yordan-Ramchev** [comment]
Yarn's documentation not explicitly list `yarn create` under its own section due to the evolution of Yarn and its features, but `yarn create` is not deprecated and it's still working. 

Using `create` command:
<img width="858" alt="Screenshot 2024-06-15 at 10 57 58" src="https://github.com/vuejs/create-vue/assets/69005114/ef16813b-6f25-4dc0-bd9f-f848eace2eef">


Using `yarn dlx` for project initialization is a supported, and maybe `yarn` is moving in that direction.

Using `dlx` command (feature flags are working):
<img width="858" alt="Screenshot 2024-06-15 at 10 57 33" src="https://github.com/vuejs/create-vue/assets/69005114/79e3f86d-a3da-4b4e-898b-0adb5b4d0e72">

Maybe creating an issue in https://github.com/vuejs/docs and reference this discussion would be a good starting point.

**Comment by 2239058652** [comment]
> 你好！
> 
> 我决定借助`create-vue`和`yarn`工具创建一个新的 Vue 项目。我运行`yarn create vue@latest`并设置了以下选项： ✔ 项目名称：… vue-project ✔ 添加 TypeScript？… 是 ✔ 添加 JSX 支持？… 是 ✔ 添加 Vue Router 进行单页应用程序开发？… 是 ✔ 添加 Pinia 进行状态管理？… 是 ✔ 添加 Vitest 进行单元测试？… 否 ✔ 添加端到端测试解决方案？› 否 ✔ 添加 ESLint 以提高代码质量？… 是 ✔ 添加 Prettier 进行代码格式化？… 是
> 
> 然后我进入`vue-project`文件夹，运行`yarn`命令并看到以下内容： ![图像](https://user-images.githubusercontent.com/20267977/207309377-7b5bbfc3-27ef-4a97-b41e-a2c1ffbc119c.png)
> 
> 我能做些什么来快速解决这个问题？ 谢谢。
just yarnset version stable can ok
