### ISSUE TITLE
How to re-initialize create-vue

### ISSUE THREAD

**Issue by janswist** [vuejs/create-vue#228]
I'm wondering how can I add TypeScript or Cypress using `npm init vue@3` - so when I call it on existing project I can just select missing functionalities and have it done.

Is that possible?

**Comment by btea** [comment]
This seems impossible, if you initialize in a folder that already has files and use `.` as the project name, it will delete all files and then initialize.

**Comment by janswist** [comment]
Thanks for the reply. I figured it was a thing in Vue 2: https://stackoverflow.com/questions/75420181/how-to-re-initialize-vue-3-scaffolding/75420280#75420280

Would be nice to have same in Vue 3, though. When side project grows to bigger one and needs implementing tests or to add Pinia.
