### ISSUE TITLE
Conflict between ESLint, Prettier, and VS Code Auto Formatting on Save

### ISSUE THREAD

**Issue by hcljsq** [vuejs/create-vue#236]
I used `create-vue` to create a new project with both `ESLint` and `Prettier` enabled.

I also configured VS Code to auto-format on save without any additional customizations.

When I ran `npm run lint`, I got the formatting results I wanted. However, when I hit `ctrl` + `S` to save, the formatting changed to a style I did not want. This has caused a conflict, and I'm not sure how to resolve it. Could you please help me understand what's causing this and how to fix it?

Thank you. ❤️

**Comment by ebisbe** [comment]
Have you set 'prettier/prettier' as an error on the eslint file? 

Like this:
```
rules: {
    'prettier/prettier': 2
  },
```
