### ISSUE TITLE
Vue's tsconfig.json broken with Typescript 5

### ISSUE THREAD

**Issue by jez9999** [vuejs/create-vue#243]
### Vue version

3.2.47

### Link to minimal reproduction

This is with Vue's tsconfig.json

### Steps to reproduce

If your Vue app's tsconfig.json extends Vue's, as it does in some create templates:

```
{
	"extends": "@vue/tsconfig/tsconfig.node.json",
}
```

Build is now broken in TS5 because of deprecated options.

### What is expected?

Build works OK.

### What is actually happening?

Build breaks with errors:

> error TS5101: Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.

> error TS5101: Option 'preserveValueImports' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.

Vue's `tsconfig.json` should be updated not to use the `preserveValueImports` or `importsNotUsedAsValues` options.

**Comment by sodatea** [comment]
Updated in `@vue/tsconfig` 0.3.x https://github.com/vuejs/tsconfig#migrating-from-typescript--50
