### ISSUE TITLE
Prettier and eslint doesn't work out-of-the box after install

### ISSUE THREAD

**Issue by xorik** [vuejs/create-vue#252]
Steps to reproduce:
1. Install with choosing  prettier + eslint
2. Run `npm run lint`

Expected result:
3. Spaces/empty lines fixed

Actual result:
3. Prettier/eslint rules aren't applied

![image](https://user-images.githubusercontent.com/347044/233058897-a625cb29-4f17-4a78-be58-cb2922056c45.png)

![image](https://user-images.githubusercontent.com/347044/233059178-b61a02b4-7213-4703-8cae-534682c1ac5b.png)

**Comment by yesworld** [comment]
Faced the same problem.

**Comment by sodatea** [comment]
Please run `pnpm run format`.
It's explained in the release notes https://github.com/vuejs/create-vue/releases/tag/v3.6.0
And the prompt after creating the project has been updated accordingly:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/3277634/233568695-66dcaf96-3b0e-4d73-a241-33f72cccddb2.png">
