### ISSUE TITLE
Switch to mri and yoctocolors for better performance?

### ISSUE THREAD

**Issue by so1ve** [vuejs/create-vue#253]
I can contribute to this:)

**Comment by sodatea** [comment]
- For argument parsing, I prefer to switch to the built-in `util.parseArgs` https://nodejs.org/dist/latest-v20.x/docs/api/util.html#utilparseargsconfig Maybe we can do it after Node.js v16 reaches End-of-Life so that dropping older Node.js versions won't surprise too many users.
- As for `yoctocolors`, it lacks conventional environment variables support (e.g. those listed at https://github.com/marvinhagemeister/kolorist#usage, plus `CI`, etc.;  those are commonly respected environment variables in most other color libraries)

**Comment by so1ve** [comment]
Actually yoctocolors supports environment variables. They are handled in tty.WriteStream.prototype.hasColors (a built-in node module)!

**Comment by so1ve** [comment]
And for now we can switch to mri for smaller size because util.parseArgs is still unstable.

**Comment by sodatea** [comment]
> Actually yoctocolors supports environment variables. They are handled in tty.WriteStream.prototype.hasColors (a built-in node module)!

Thanks for the info! Good to know that. Then I'm not against switching to yoctocolors.

However, I just did some research and found that `picocolors` is both smaller and more popular than `yoctocolors`. Maybe that's a better alternative?

https://packagephobia.com/result?p=picocolors
https://packagephobia.com/result?p=yoctocolors
https://npmtrends.com/picocolors-vs-yoctocolors

**Comment by so1ve** [comment]
> > Actually yoctocolors supports environment variables. They are handled in tty.WriteStream.prototype.hasColors (a built-in node module)!
> 
> Thanks for the info! Good to know that. Then I'm not against switching to yoctocolors.
> 
> However, I just did some research and found that `picocolors` is both smaller and more popular than `yoctocolors`. Maybe that's a better alternative?
> 
> https://packagephobia.com/result?p=picocolors https://packagephobia.com/result?p=yoctocolors https://npmtrends.com/picocolors-vs-yoctocolors

Maybe…? However yoctocolors seems to have better performance. Benchmark later :)

**Comment by sodatea** [comment]
Why does performance matter in the use case of `create-vue`? There are only a few calls to the color functions; the difference might be only a few μs.

**Comment by so1ve** [comment]
> Why does performance matter in the use case of `create-vue`? There are only a few calls to the color functions; the difference might be only a few μs.

Makes sense. Let's switch to picocolors!

**Comment by haoqunjiang** [comment]
I eventually switched to [`kleur/colors`](https://github.com/lukeed/kleur/) in https://github.com/vuejs/create-vue/commit/03955554ae6c065810edb1d8cebdc633c8b31464
Because turns out it produces the smallest bundle for our usage…
