### ISSUE TITLE
Cannot find base config file "@vue/tsconfig/tsconfig.web.json

### ISSUE THREAD

**Issue by laterdayi** [vuejs/create-vue#254]
failed to resolve "extends":"@vue/tsconfig/tsconfig.web.json" in \tsconfig.json
[vite:esbuild] failed to resolve "extends":"@vue/tsconfig/tsconfig.node.json" in F:/tsconfig.config.json

**Comment by antoniogiroz** [comment]
Are you using the latest version of the vue (3.3.x)? If so, you need to change:

 `"extends":"@vue/tsconfig/tsconfig.web.json"`
 
 to 

```json
"extends": [
  "@vue/tsconfig/tsconfig.json",
  "@vue/tsconfig/tsconfig.dom.json"
]
```

Check this repo: https://github.com/vuejs/tsconfig also to extend for the `.node` because probably you need to install another package.

**Comment by laterdayi** [comment]
Tsconfig.config. json and tsconfig.json only need one?

@antoniogiroz

**Comment by antoniogiroz** [comment]
I have these ones:


```json
// tsconfig.json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.vitest.json"
    }
  ]
}
```

```json
// tsconfig.node.json
{
  "extends": ["@tsconfig/node18/tsconfig.json", "@vue/tsconfig/tsconfig.json"],
  "include": ["vite.config.*", "vitest.config.*", "playwright.config.*"],
  "compilerOptions": {
    "composite": true,
    "types": ["node", "vitest"]
  }
}
```

```json
// tsconfig.app.json
{
  "extends": ["@vue/tsconfig/tsconfig.json", "@vue/tsconfig/tsconfig.dom.json"],
  "include": ["src/types/env.d.ts", "src/**/*", "src/**/*.vue"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "types": ["vue/ref-macros"],
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

```json
// tsconfig.vitest.json
{
  "extends": "./tsconfig.app.json",
  "include": ["src/types/env.d.ts", "src/**/*", "tests/unit/**/*"],
  "exclude": [],
  "compilerOptions": {
    "composite": true,
    "lib": [],
    "types": ["node", "jsdom"]
  }
}
```

**Comment by laterdayi** [comment]
```
https://github.com/vuejs/tsconfig
```

@antoniogiroz  In the latest tsconfig, tsconfig.node.json seems to have been deleted. In this case, how should you modify it

**Comment by segevfiner** [comment]
`create-vue` should probably be updated to accommodate the new `@vue/tsconfig`, then you can just copy whatever the template does for a new project. Otherwise you can downgrade to `@vue/tsconfig<0.2`

**Comment by antoniogiroz** [comment]
> ```json
> @tsconfig/node18/tsconfig.json
> ```

In my example tsconfig.node.json I'm extending from `@tsconfig/node18/tsconfig.json`. You need to install this package.

https://github.com/vuejs/tsconfig

**Comment by logue** [comment]
When I tried this method, a ts(2345) error occurred where a `component` tag was used like: 

```vue
<component :is="'div'">
  foo
</component>.
```

**Comment by sodatea** [comment]
0.2.x / 0.3.x should be considered a major update, according to semver, so breaking changes are expected.
The migration path is now documented in `@vue/tsconfig`'s README https://github.com/vuejs/tsconfig#migrating-from-typescript--50
