### ISSUE TITLE
Vitest support

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/create-vue#27]
I spotted [a comment in a recent commit](https://github.com/vuejs/create-vue/blob/f97d72424d4fd97ac0a77bc94ce55db476e849ef/utils/renderEslint.js#L75) about Vitest support.

That would be great, and probably a better alternative than [Jest support](#6 ).

I would be willing to help move this forward if nobody is working on this

I suppose we would add a `--vitest` flag.

How do you plan to integrate with the current `--tests` flag? 

Something like: if both `--cypress` and `--vitest` are present, use Vitest for unit test, and use Cypress for e2e, otherwise, if only cypress is present, use it for both (as `--tests` does now)?

It will also add other combinations for the playground: is it OK? (`jsx-pinia-vitest`, `jsx-pinia-cypress`, `jsx-pinia-vitest-cypress`, `jsx-router-vitest`, etc...)

**Comment by sodatea** [comment]
> I would be willing to help move this forward if nobody is working on this

That will be great!

> I suppose we would add a `--vitest` flag.

Agree.

> How do you plan to integrate with the current `--tests` flag?
> 
> Something like: if both `--cypress` and `--vitest` are present, use Vitest for unit test, and use Cypress for e2e, otherwise, if only cypress is present, use it for both (as `--tests` does now)?

Mostly agree.
I suggest that we change how `--test`/`--with-tests` works now, defaulting to Vitest for unit test and Cypress for e2e. Because Vitest works better in headless CI environments than Cypress Component Testing.

`--cypress` without `--vitest` can use Cypress for both unit and e2e tests.

> It will also add other combinations for the playground: is it OK? (`jsx-pinia-vitest`, `jsx-pinia-cypress`, `jsx-pinia-vitest-cypress`, `jsx-router-vitest`, etc...)

Yeah, that's totally fine.

**Comment by sodatea** [comment]
Implemented at https://github.com/vuejs/create-vue/pull/29

**Comment by sodatea** [comment]
Released as 3.1.0
