### ISSUE TITLE
how to use tsconfig.json

### ISSUE THREAD

**Issue by Sami-zzz** [vuejs/create-vue#272]
Now the root directory has three configuration files: tsconfig.json, tsconfig.app.json, and tsconfig.node.json. My code runs in the browser. If I want to add some configuration, where should I write it?

**Comment by filipbekic01** [comment]
Depends on configuration you want. Most likely in tsconfig.app.json but nobody stops you from adding even more configuration files. Your root tsconfig.json will invoke app.json and node.json.

**Comment by Sami-zzz** [comment]
Thanks! Because I encountered some bugs, but later found out that it was caused by the upgrade of typescript.
