### ISSUE TITLE
tsconfig文件进行拆分后，element-plus设置全局类型没有效果了

### ISSUE THREAD

**Issue by wwhtml** [vuejs/create-vue#273]

**Comment by sodatea** [comment]
请提供完整复现代码

**Comment by wwhtml** [comment]
tsconfig.node.json
![360截图18510713127051](https://github.com/vuejs/create-vue/assets/86592510/c8ea3e9e-cd29-45d9-a7ed-c3c63663bc89)
![360截图174308155679101](https://github.com/vuejs/create-vue/assets/86592510/c65e7bd2-2415-40e8-8467-632d11544a5c)
![360截图17400115073332](https://github.com/vuejs/create-vue/assets/86592510/bd623aa9-49be-4a0f-98a4-b95d49b03962)

之前配置好之后鼠标放在el-button之上会提示类型，现在没有了

**Comment by sodatea** [comment]
放错文件了。这个文件是 tsconfig.node.json，你要写在 tsconfig.app.json 里
