### ISSUE TITLE
Starter example: icons style regression from fixed issue #271

### ISSUE THREAD

**Issue by DJ-caddev** [vuejs/create-vue#282]
A regression has appeared in the latest create-vue version '2023-05-12 (v3.6.4)', in the starter project.

The commented line below has been removed from the base example:
```
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  /* position: relative; */
  font-weight: normal;
}
```

causing the page to display as such, with all the icons packed on the center-left of the screen:
![image](https://github.com/vuejs/create-vue/assets/93262194/5aa85d1e-6d13-4a89-bb44-d920bf925b35)

**Comment by btea** [comment]
Seems to have been fixed by #278
