### ISSUE TITLE
Fix type definitions with vue-create & vuex

### ISSUE THREAD

**Issue by messenjer** [vuejs/create-vue#291]
Hello, 

When using the latest version of create-vue with typescript 5 and vuex, we get an error.

```
src/store/index.ts - error TS7016: Could not find a declaration file for module 'vuex'.
'node_modules/vuex/dist/vuex.mjs' implicitly has an 'any' type.
  There are types at 'node_modules/vuex/types/index.d.ts', but this result could not be resolved
when respecting package.json "exports". The 'vuex' library may need to update its package.json or typings.
```

There are quite a few issues about this on the Vuex repo, but nobody fixes it : 
- https://github.com/vuejs/vuex/issues/2213 
- https://github.com/vuejs/vuex/issues/2223
 
In the replies, users explain that Vuex is no longer maintained.

Given that Vuex is a Vue project, would it be possible to apply the fix?

https://github.com/vuejs/vuex/pull/2219 
https://github.com/vuejs/vuex/pull/2220

Thanks in advance

Mathieu

**Comment by liuwenzhi0318** [comment]
我这两天也是一直这样，找不到问题

**Comment by messenjer** [comment]
I'm using https://github.com/ds300/patch-package to apply the fix for vuex and vuei18n.

As it's an issue with vuex, I'm closing the issue here.

**Comment by boravia** [comment]
> 我这两天也是一直这样，找不到问题

have you found the solution?
