### ISSUE TITLE
Include management for https certs at dev time

### ISSUE THREAD

**Issue by fabiodp1** [vuejs/create-vue#298]
Hi, is it possible to include in the vite dev server configuration the management or use of a plugin ([vite-plugin-mkcert](https://github.com/liuweiGL/vite-plugin-mkcert)) for certs management? Since chromium based browsers don't permit http anymore, even for localhost.
Thanks
![Image 001](https://github.com/vuejs/create-vue/assets/18539997/a9990b53-bbe4-4852-b772-41350d7a4ebf)

**Comment by fabiodp1** [comment]
Hi @cexbrayat !
Yep I was thinking about adding it by default, or thinking about creating an implementation activable by config.
I think that like me most part of the people develope in local, and using a chromium based browser, so that it will be ALLWAYS necessary to install that plugin.

**Comment by cexbrayat** [comment]
Thanks for your answer @fabiodp1 
I don't think it is mandatory by default (at least it is not for all the teams I work with in various companies). Maybe you have a special setting somewhere?

**Comment by fabiodp1** [comment]
@cexbrayat I'll check if it is some setting that is preventing me to work in http. Thanks for your reply and interest. 👋

**Comment by cexbrayat** [comment]
@fabiodp1 I'll go ahead and close this. If you find that it is not possible to work without this in some environments, feel free to open a PR to improve the scaffolding and we'll gladly review it!

**Comment by bmulholland** [comment]
If there was a good place for docs that cover next steps after using create-vue, a quick writeup of how to do HTTPS via mkcert would be a good compromise for this. Not in the scaffold, but still easy to add for those who need it.

**Comment by cexbrayat** [comment]
I think the vitejs docs are where you should look for this, and they already mention a few things (like https://vitejs.dev/config/server-options.html#server-https). If that's not clear enough, maybe you can open an issue there and explain what you need (or even better open a PR to improve the docs if you can).

**Comment by bmulholland** [comment]
Yeah, I guess my point is better aligned with a better discussion of how to connect the dots from the resulting scaffold to all these other places. It's a big jump from "install scaffold" to knowing what Vite is, understanding that it's the right place to look for docs, and so forth. Also, arguably, instructions on "how to set up HTTPS certs" is closer to the create-vue project than Vite, which would probably say that the instructions I describe are the responsibility of the mkcert... and then that's all describing the status quo. Which, again, requires a newcomer to understand a lot, all at once. So: different topic.
