### ISSUE TITLE
Do not include empty Prettier config file

### ISSUE THREAD

**Issue by aentwist** [vuejs/create-vue#304]
## Description

Including an empty file in a template is silly. Especially when Prettier itself would probably encourage you not to use the file. The mission statement of Prettier is to be 'an opinionated formatter', taking the configuration out of formatting with opinionated defaults.

You could say, well it's simple to delete. Sure, but I say, well it's simple to create. I would wager the majority of Prettier users are not using this file. Especially given Prettier's attitude.

See also #300

**Comment by sodatea** [comment]
The official Prettier documentation encourages users to "create an empty config file to let editors and other tools know you are using Prettier".
It is not silly.

**Comment by sodatea** [comment]
https://prettier.io/docs/en/install.html#:~:text=create%20an%20empty%20config%20file%20to%20let%20editors%20and%20other%20tools%20know%20you%20are%20using%20Prettier
