### ISSUE TITLE
Upgrading/removing dependency to `npm-run-all`

### ISSUE THREAD

**Issue by Ericlm** [vuejs/create-vue#306]
When creating a new vue project with `npm init vue@latest` and by checking typescript support, it automatically brings the package [npm-run-all](https://github.com/mysticatea/npm-run-all). However, this package did not received any update since 2018 (and suffers from a moderate vulnerability via `semver`). Maybe would it be best to move from it, or finding alternatives ?

Thank you!

**Comment by ModyQyW** [comment]
I am using https://github.com/open-cli-tools/concurrently as an alternative. Looks good to me so far.
