### ISSUE TITLE
When scaffolding new app, TypeScript Error in vitest.config.ts

### ISSUE THREAD

**Issue by dustin-downs** [vuejs/create-vue#313]
When scaffolding a new app with TypeScript and Vitest using `npm init vue@latest`, there's a TypeScript error in _vitest.config.ts_ related with the usage of mergeConfig.

> 
> Argument of type 'UserConfigExport' is not assignable to parameter of type 'UserConfig | Promise<UserConfig>'.
>   Type 'UserConfigFn' is not assignable to type 'UserConfig | Promise<UserConfig>'.ts(2345)

It seems the actual types in use for the "mergeConfig" arguments are **UserConfigExport**, but "mergeConfig" is expecting them to be of type **UserConfig**.

Here are the prompt selections:
![Screenshot 2023-07-10 at 9 30 50 AM](https://github.com/vuejs/create-vue/assets/2736672/78b82ec9-d38e-41ab-9b1c-c9cc6f406e68)

After installing dependencies, the following error shows up in _vitest.config.ts_:
![Screenshot 2023-07-10 at 9 27 30 AM](https://github.com/vuejs/create-vue/assets/2736672/7855cbfd-c48b-4eb3-b564-85fa500ba349)

**Comment by sodatea** [comment]
Workaround:
1. Update Vite to the latest version
2. Then apply this patch: https://github.com/vuejs/create-vue/commit/b948832388366c040d7dc7bad30a7daa513c11c3
