### ISSUE TITLE
There is no immediate change to the computed attribute assignment

### ISSUE THREAD

**Issue by suzhenghui-sky** [vuejs/create-vue#315]
![图片](https://github.com/vuejs/create-vue/assets/48371536/9b8c84c0-c375-479e-bd94-44a47d45e426)
![图片](https://github.com/vuejs/create-vue/assets/48371536/88237765-498d-40b0-89d3-8641826a51d7)
![图片](https://github.com/vuejs/create-vue/assets/48371536/50efda19-4c40-4337-9cd4-ea1e2676172c)

**Comment by cexbrayat** [comment]
Hi @suzhenghui-sky 

I don't think this is an issue with create-vue: create-vue just generates the project.
If you think there is an issue with Vue 3, create a small reproduction (you can use Stackiblitz https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts) and open an issue on the vuejs/core repo.

In the meantime, I'll close this one
