### ISSUE TITLE
How can a parent dynamically add a type to a child component

### ISSUE THREAD

**Issue by suzhenghui-sky** [vuejs/create-vue#316]
I have a generic loop component, but the type is unknown and cannot be referenced properly。
![图片](https://github.com/vuejs/create-vue/assets/48371536/bdb0823d-a9ba-4be9-bd22-43839b0b91e1)

**Comment by cexbrayat** [comment]
Hi @suzhenghui-sky 

Take a look at https://github.com/vuejs/rfcs/discussions/436 : it allows specifying a generic type on a component in Vue 3.3.

As this is not an issue with create-vue, I'll close this
