### ISSUE TITLE
Vite fresh install: TypeScript error for vitest.config.ts

### ISSUE THREAD

**Issue by marvhock** [vuejs/create-vue#317]
See issue [on Discord](https://discord.com/channels/804011606160703521/1128080105701380257/1128080105701380257)

Hi!

I just made a fresh install (vue@3.3.4, vite@4.4.6)`npm init vue@latest`.
Sadly I have a TS Error in vitest.config.ts:7

```export default mergeConfig(
  viteConfig,
  defineConfig({
    test: {
      environment: 'jsdom',
      exclude: [...configDefaults.exclude, 'e2e/*'],
      root: fileURLToPath(new URL('./', import.meta.url)),
      transformMode: {
        web: [/\.[jt]sx$/]
      }
    }
  })
)
```

The Error says the following.
S2345: Argument of type 'UserConfigExport' is not assignable to parameter of type 'UserConfig | Promise<UserConfig>'.   Type 'UserConfigFn' is not assignable to type 'UserConfig | Promise<UserConfig>'.

Question:
* Can I fix it, or is it only able inside the Vite Package itself? Is there an Update to fix that?
* Is it bad to have a TS error (like that) on a fresh install. Should I worry about TS Errors or are they not important?

**How to Reproduce**
1. Open Terminal on mac, run `npm create vite@latest`
2. Follow the install instructions using: TS, TSX, VueRouter, Piania, Vitest, Cypress, ESlint, prettier
3. run. cd <myproject> && npm i && npm run format && npm run dev
4. In Webstorm I get that error in the file after File-Indexing is finished in Webstorm

**Comment by sodatea** [comment]
> * Can I fix it, or is it only able inside the Vite Package itself? Is there an Update to fix that?

1. Update Vite to the latest version
2. Then apply this patch: https://github.com/vuejs/create-vue/commit/b948832388366c040d7dc7bad30a7daa513c11c3

> * Is it bad to have a TS error (like that) on a fresh install. Should I worry about TS Errors or are they not important?

It's bad, but not that important. The code still runs despite the type issue.
The `type-check` command only checks `src` at the moment, as they are the most important ones.
That's also why we didn't catch the issue in our own tests.
(We are considering making it more comprehensive, though https://github.com/vuejs/create-vue/pull/274)
