### ISSUE TITLE
vue-cli / vite / create-vue / etc?

### ISSUE THREAD

**Issue by lorand-horvath** [vuejs/create-vue#32]
Sorry for not understanding, but can anyone explain what is going on with the vue tooling?
During the last year or so, several dev tools have popped up, i.e. vue-cli, vite, create-vue etc
I would appreciate if someone would explain why use one over the other and which one to use? It's confusing and creating fragmentation in the community. Thanks.

**Comment by web2033** [comment]
https://staging.vuejs.org/guide/scaling-up/tooling.html#project-scaffolding
