### ISSUE TITLE
Use argv but not working

### ISSUE THREAD

**Issue by gkf442573575** [vuejs/create-vue#326]
### Any feature flags are set, and the feature prompts are still not skipped

node@16.9.0
npm@8.19.3

my shell
```bash
npm create vue@latest test --default --ts --jsx --router --pinia --tests false --vitest false --cypress false --nightwatch false --playwright false --eslint --eslint-with-prettier
```

**Comment by zhhbstudio** [comment]
too many flags
you can try this: ` npm create vue@latest test --default `

**Comment by zhhbstudio** [comment]
after npm@6，you need  ` -- ` before you args, you can run this `npm create vue@latest test -- --default `
