### ISSUE TITLE
why use js without jsconfig.json?

### ISSUE THREAD

**Issue by yp498517645** [vuejs/create-vue#334]
![image](https://github.com/vuejs/create-vue/assets/72730929/9f7d8706-5b09-45ca-be97-472dda2576a6)

**Comment by cexbrayat** [comment]
Hi @yp498517645 

Can you explain a bit more what you would like? Is there an issue if you don't have a jsconfig file? If so, can you provide us a small repro using Stackblitz for example?

**Comment by cexbrayat** [comment]
A jsconfig.json file has been added to the generated project thanks to https://github.com/vuejs/create-vue/pull/102
