### ISSUE TITLE
new project hosting not working on windows 11

### ISSUE THREAD

**Issue by mark-hahn** [vuejs/create-vue#335]
I created a new Vue/Vite project with *vue create* in a commend window in windows 11.  I then chose the default setup.  After it ran awhile setting up I ran vite and got 
```
  VITE v3.0.2  ready in 188 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
```
Then I went to http://127.0.0.1:5173 in my chrome browser and got 
```
This 127.0.0.1 page can’t be found
No webpage was found for the web address: http://127.0.0.1:5173/
HTTP ERROR 404
```
Can someone please give me a hand?

**Comment by mark-hahn** [comment]
I used *npm create vue@latest* instead and everything worked.  Why doesn't *vue create* work?

**Comment by zhhbstudio** [comment]
Try to visit http://localhost:5173

**Comment by sodatea** [comment]
As said in the project README:

> Note that the tag name (`@latest` or `@legacy`) MUST NOT be omitted, otherwise `npm` may resolve to a cached and outdated version of the package.

This can be seen from your console output:
```
  VITE v3.0.2  ready in 188 ms
```

Vite 3.0.2 is a very outdated version. The latest is 4.4.9.
