### ISSUE TITLE
A project created with create-vue failed to add a new route

### ISSUE THREAD

**Issue by 18380468559** [vuejs/create-vue#363]
![f2406fa28f0f603c2b9705f56901b1b](https://github.com/vuejs/create-vue/assets/83292142/26bb2ef9-4f81-401e-ab1d-47e1a0545b91)

**Comment by cexbrayat** [comment]
Hi @18380468559 

Do you have an error when running `npm run type-check`?

**Comment by 18380468559** [comment]
> Hi @18380468559
> 
> Do you have an error when running `npm run type-check`?

No error is reported when 'npm run type-check' is run
![37823823f20eb6a2bbac0ea27153c57](https://github.com/vuejs/create-vue/assets/83292142/df2f79e1-f7ec-4ba3-81a6-07a0a2ff6440)

**Comment by cexbrayat** [comment]
OK, so there is no TypeScript error, and your application should work: it's probably just VSCode that doesn't see the file.
You can try to restart the typescript service in VSCode, sometimes it helps.
