### ISSUE TITLE
pnpm create vue@legacy or pnpm create vue@2 error warning

### ISSUE THREAD

**Issue by getr00t** [vuejs/create-vue#370]
I use the command pnpm create vue@2 to build the vue2+vite+js project. I did not select ts. Why does the component show lang=ts?
There are also a proliferation of commands to build vue projects, vue create my-vue-app, pnpm create my-app-vue, pnpm create vue@2, pnpm create vue@3, (pnpm create vite official website says this), What are the differences between these different commands? Are these different build commands officially maintained? Why are there so many different build commands? Feeling illegally confused and confused as to which one should be used.
![vite+vue2](https://github.com/vuejs/create-vue/assets/12257416/026585f0-1866-439d-a3bd-4e883b12ecbf)
![goujian](https://github.com/vuejs/create-vue/assets/12257416/8ac47778-7a41-4f52-9a7f-366b609f0e87)
Related code:

[https://github.com/vuejs/create-vue/blob/v2/template/code/router/src/views/HomeView.vue#L1](url)

**Comment by cexbrayat** [comment]
This has been fixed thanks to @btea PR in #374 , thanks!

**Comment by cexbrayat** [comment]
It's not released yet
