### ISSUE TITLE
'create vue@2' exception 

### ISSUE THREAD

**Issue by YangFong** [vuejs/create-vue#371]
It shouldn't be here:
 
<img width="834" alt="image" src="https://github.com/vuejs/create-vue/assets/70502828/265af805-51a7-4fae-9546-af880a73e3b2">

Reproduction step:

<img width="724" alt="image" src="https://github.com/vuejs/create-vue/assets/70502828/282e10e5-12b5-43b9-91f3-ff7b6906770e">

Related code:

https://github.com/vuejs/create-vue/blob/v2/template/code/router/src/views/HomeView.vue#L1

**Comment by cexbrayat** [comment]
Hi @YangFong 
Thanks for the report

This is a duplicated of #370 so I'll close this one
