### ISSUE TITLE
Use vitest to make unittest

### ISSUE THREAD

**Issue by CoolPlayLin** [vuejs/create-vue#376]
Currently, *create-vue*'s testing script only includes `test.mjs`. I'd like this project to use vitest to test functions

**Comment by cexbrayat** [comment]
Yes, I think it could be handy as well 👍
If you feel like opening a PR, we'll gladly review it.

**Comment by CoolPlayLin** [comment]
I'd like to open PR. It would take a while

**Comment by CoolPlayLin** [comment]
Oh no, I cannot install vitest via pnpm
![image](https://github.com/vuejs/create-vue/assets/96709586/3e63460b-36bf-410c-96b2-24707800c44c)
