### ISSUE TITLE
Use Vite 5 

### ISSUE THREAD

**Issue by SirMishaa** [vuejs/create-vue#379]
Hello, 

Vite 5 just has been released 
https://vitejs.dev/blog/announcing-vite5

The performance boost and new features are interesting. I propose to bump the version of vite. 
What do you think about it ?

**Comment by cexbrayat** [comment]
Yes, we will of course bump to Vite 5.
Renovate will probably open a PR soon with this version, and we'll see if everything is OK, and then we can merge and release it in the next weeks.

In the meantime, you can bump vite in your own projects.
