### ISSUE TITLE
Improved, clear documentation needed

### ISSUE THREAD

**Issue by lorand-horvath** [vuejs/create-vue#38]
I've posted the following in the `vue-cli` repo https://github.com/vuejs/vue-cli/commit/7f3d51133635114528848b29e27084ee89d53e1c#comments
- thought it would be wiser to raise the issue here as well:

@yyx990803 Thanks for clarifying the fact that Vue CLI is now in maintenance mode and that you discourage its use for new Vue 3 projects.
I would recommend adding some proper, detailed documentation for the new Vite-based scaffolding tool `create-vue` because at the moment it's not trust inspiring - it is rather minimal and lacking any description.
Otherwise a lot of developers will probably stick to webpack-based `vue-cli` - this is the situation I am in now. I'd rather use Vue CLI 5 still in beta/rc than jump the ship from the tried-and-true webpack-based tooling, to new bells and whistles (just because it's seemingly faster).

**Comment by lorand-horvath** [comment]
Yeah... thought so. Hmm...

**Comment by sodatea** [comment]
Just for the record:
- I didn't close this issue because I agree that the documentation needs to be improved; I do appreciate your enthusiasm.
- I didn't reply earlier because I was *too damn busy* to think about this problem for the past few days. It's been too stressful.

**Comment by sodatea** [comment]
As for my personal priority queue, here's the background:
- Unlike `create-react-app` or `@vue/cli`, this project is merely a scaffolding tool. All the actual bundling, type checking… are done by other tools such as Vite or `vue-tsc`, etc. So I don't think there's much to document here; Vite has its own documentation.
- The usage of this tool, and many parts of the logic behind the technical decisions are already covered in the new Vue documentation (staging.vuejs.org), which will become the default on Feb. 7th. You don't have to look at this repository to get more info.

So, my focus in the short term would be:
1. Improve the tool itself. It's already very minimal. So I'm gonna improve the prompt, add more descriptions to each question, and maybe i18n;
2. Improve the visibility of this tool: integrate it into `create-vite`'s Vue template so that there won't be too much fragmentation in the ecosystem;
3. Ship Vue CLI 5 stable.

**Comment by LinusBorg** [comment]
@sodatea Some people feel entitled to our immediate attention when in fact they are not. Let's apprechiate they ejected
themselves and we can work on this on our terms.

**Comment by lorand-horvath** [comment]
@LinusBorg No, I don't feel entitled to anything, but I do feel that the community has been fragmented quite badly since everything in the ecosystem at the moment is either in beta, RC, staging or undocumented or not yet released. It has been like this for quite some time now. I'm not blaming anyone, but that's the situation, which I hope will be improved soon...

You're welcome to appreciate it, but I haven't "ejected" myself from anything Vue-related. I only said I just might... speaking rhetorically.
It's interesting that people react (pun intended) only if someone gets a little bit angry. Otherwise, we don't seem to be getting much feedback from the esteemed developers/maintainers for many days or even weeks. I'm sorry, but just a couple of years ago the situation was much more engaging, as far as I remember.

@sodatea Thanks for the heads up, I really appreciate it!

**Comment by sodatea** [comment]
> It's interesting that people react (pun intended) only if someone gets a little bit angry.

That's absolutely toxic mentality.
What can you get from doing this aside from making me feel guilty and become even more burnt out during my holidays??!

> Otherwise, we don't seem to be getting much feedback from the esteemed developers/maintainers for many days or even weeks. I'm sorry, but just a couple of years ago the situation was much more engaging, as far as I remember.

It is an unrealistic expectation, especially in the OSS community.

In case you don't know, guaranteed response time is a paid service in the real world. It costs real money.

**Comment by lorand-horvath** [comment]
@sodatea It seems both of you are offended because I asked a few questions. I am very sorry, I didn't mean it.
But saying that's toxic mentality and that I have unrealistic expectations, I don't agree.
I did say I appreciate your work and I say it again.

Maybe it's me. Perhaps I am the one who doesn't understand this community or the way things happen lately... I will try to gather more information and reflect on this.

Thanks for taking the time to reply.

**Comment by lorand-horvath** [comment]
> absolutely toxic mentality

@sodatea Thanks.
