### ISSUE TITLE
An error occurred when adding a route

### ISSUE THREAD

**Issue by 18380468559** [vuejs/create-vue#382]
When I create a TypeScript project with `npm create vue@latest`, then add a new '.vue' file to the views folder, and then add the route to 'index.ts' in the router folder, ts prompts:

> File 'd:/proj-temp/my-vue-proj/src/views/MyView.vue' is not listed within the file list of project  'd:/proj-temp/my-vue-proj/tsconfig.app.json'. Projects must list all files or use an 'include' pattern.

I started a new project with `npm create vue@latest` like so:

✔ Add TypeScript? … No / **Yes**
✔ Add JSX Support? … No / **Yes**
✔ Add Vue Router for Single Page Application development? … No / **Yes**
✔ Add Pinia for state management? … No / **Yes**
✔ Add Vitest for Unit Testing? … **No** / Yes
✔ Add Cypress for End-to-End testing? … **No** / Yes
✔ Add ESLint for code quality? … No / **Yes**
✔ Add Prettier for code formatting? … No / **Yes**

Create a new`.vue` file in the views folder:

```vue
<template>
  <div>
    <h1>my view</h1>
  </div>
</template>

<style></style>
```

Add the route to index.ts in the router folder:

```typescript
import { createRouter, createWebHistory } from 'vue-router'
import HomeView from '../views/HomeView.vue'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: '/',
      name: 'home',
      component: HomeView
    },
    {
      path: '/about',
      name: 'about',
      // route level code-splitting
      // this generates a separate chunk (About.[hash].js) for this route
      // which is lazy-loaded when the route is visited.
      component: () => import('../views/AboutView.vue')
    },
   // This is the newly added route, and TypeScript will prompt errors here, with screenshots at the end of the article
    {
      path: '/my',
      name: 'my',
      component: () => import('../views/MyView.vue')
    }
  ]
})

export default router

```

My tsconfig.json file:

```json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    }
  ]
}

```

My tsconfig.app.json file:

```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}

```

ts error message:

![image](https://github.com/vuejs/create-vue/assets/83292142/3c800be2-ecf5-4003-8926-97921ed95b53)

**Comment by cexbrayat** [comment]
Hi @18380468559 

Do you have an error when you run `npm run type-check`?

**Comment by cexbrayat** [comment]
Closing this as we did not hear back from the OP.

If this is a reproducible issue, feel free to ping me and I'll reopen this.
