### ISSUE TITLE
May I ask when the latest version of create-vue can be released? (2023-10-21 to latest)

### ISSUE THREAD

**Issue by vasttian** [vuejs/create-vue#384]
@sodatea May I ask when the latest version of create-vue can be released? (2023-10-21 to latest)

Thx~

**Comment by cexbrayat** [comment]
Hi @vasttian 

I don't think we have a specific timeline, but we landed a few fixes recently and we are working on a better support of Vite v5 out of the box. So we probably want to get that done before a new release.
