### ISSUE TITLE
How to make the scaffolding files created inside the current directory, without creating a new folder

### ISSUE THREAD

**Issue by hannah23280** [vuejs/create-vue#395]
Hi all,

      I executed npm init vue@latest, followed by answering the typical questions (typescript, jsx, etc).  This resulted in a new project folder being created. How do we let the scaffolding files to be created inside the current directory, without creating a new folder

**Comment by cexbrayat** [comment]
Hi @hannah23280 

I don't think you can do that. If you don't specify a project name, a `vue-project` directory will be created.

But you can manually move the files wherever you like when the project has been generated.
