### ISSUE TITLE
How to test js/ts only files ?

### ISSUE THREAD

**Issue by fabien-ml** [vuejs/create-vue#4]
Since there is no `jest` and the `test:unit` command is configured to run cypress how do we unit test js/ts files that doesn't contains any vue stuffs? 
For example a `todoApi.ts` that contains just business logic to fetch todos.

**Comment by sodatea** [comment]
An example: https://github.com/cypress-io/cypress-example-recipes/blob/3002e636740233cd6e1443344b4ceb2a25b4636c/examples/unit-testing__application-code/cypress/integration/unit_test_application_code_spec.js
