### ISSUE TITLE
Vue recommends enabling isolatedModules, but tsconfig from create-vue doesn't

### ISSUE THREAD

**Issue by bmulholland** [vuejs/create-vue#401]
See https://vuejs.org/guide/typescript/overview#configuring-tsconfig-json

Only reference to that config option in this repo is disabling it for Cypress

**Comment by cexbrayat** [comment]
It does actually: the tsconfig file extends a base configuration:
```
"extends": "@vue/tsconfig/tsconfig.dom.json",
```

this is a dependency you have in your package.json, that you can check (or in this repo https://github.com/vuejs/tsconfig)

The base config does not use `isolatedModules`, but uses `verbatimModuleSyntax` which is a superset of `isolatedModules` (see https://github.com/microsoft/TypeScript/issues/53601#issuecomment-1498239566)

**Comment by bmulholland** [comment]
Aha, thanks. FYI, I'd checked vue-tsc --showConfig before posting, but didn't know that `verbatimModuleSyntax` was a superset.

**Comment by bmulholland** [comment]
The tsconfig settings (not this project... tsc world) are an absolute disaster, so hard to grok and debug.
