### ISSUE TITLE
Using --nightwatch  will give out several warnings with npm create 

### ISSUE THREAD

**Issue by mercmobily** [vuejs/create-vue#417]
### Vue version

3

### Link to minimal reproduction

Needs to run npm to reproduce

### Steps to reproduce

npm create vue@latest test --  --router --pinia --with-tests --nightwatch --vitest --eslint --nightwatch --eslint-with-prettier --force

### What is expected?

No warnings

### What is actually happening?

**nightwatch:**
npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm WARN deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm WARN deprecated loupe@2.3.4: Please upgrade to 2.3.7 which fixes https://github.com/advisories/GHSA-4q6p-r6v2-jvc5

**@nightwatch/vue**
npm WARN deprecated sinon@15.2.0: 16.1.1

### System Info

```shell
node 20
```

### Any additional comments?

I have already created an issue for the nightwatch repo here: https://github.com/nightwatchjs/nightwatch/issues/3983 This issue will hopefully track the nightwatch one, and we will close it once they fix it.

**Comment by LinusBorg** [comment]
I don't think there's any need for us to track deprecation warnings of transitive dependencies of nightwatch. 


1) deprecation warnings like these are very common 
2) It's usable with these warnings just fine
3) we can't resolve them
4) and they need to be resolved in the nightwatch repo anyways, where you opened an issue already.

**Comment by mercmobily** [comment]
OK sorry for the noise.
