### ISSUE TITLE
[plugin:vite:import-analysis] Failed to resolve import "assets/logo.svg" from "src/App.vue". Does the file exist?

### ISSUE THREAD

**Issue by geekmister** [vuejs/create-vue#438]
### Description

1. Error to lanuch project by `npm run dev` command, the project that to use create-vue generated.
2. details error info: `[plugin:vite:import-analysis] Failed to resolve import "assets/logo.svg" from "src/App.vue". Does the file exist?`
3. screenshot

    <img width="879" alt="image" src="https://github.com/vuejs/create-vue/assets/45185145/e917db5f-7cbb-4747-9354-fc6cbceb3e75">
    <img width="1440" alt="image" src="https://github.com/vuejs/create-vue/assets/45185145/b6c58ea5-0978-41cd-93a1-68ebd1774e70">

4. I modify src of img property to `@/assets/logo.svg`, then this issue is resoloved.

### Package information

1. create-vue@3.9.1
6. nodejs v18.16.0
7. npm@9.5.1

**Comment by cexbrayat** [comment]
The `App.vue` file created should contain `./assets/logo.svg` (see https://github.com/vuejs/create-vue/blob/main/template/code/default/src/App.vue#L8)

If you remove the leading dot, then yes the file resolution no longer works but that's expected.

I don't think this is an issue with create-vue, so Ill close this

**Comment by geekmister** [comment]
Understand! It's nothing that the leading dot when generat the project with create-vue. Read your comments, I think the issue is not belong to create-vue. Thanks...

**Comment by MrShnaider** [comment]
I just created a new app using `npm create vue@latest .`and my property looked like this `src="@/assets/logo.svg"`. But when I moved the entire project to another directory using phpstorm, it removed the prefix `@/' ->  `src="assets/logo.svg"`. If someone has the same situation, just add this prefix with your hands
