### ISSUE TITLE
Use Pinia in an app created with Pinia

### ISSUE THREAD

**Issue by mterczynski** [vuejs/create-vue#440]
Expected: When creating a Vue app by `npm create vue@latest` and choosing to use Pinia, Pinia is used in the application and its effect can be seen in the web application in the browser.
Actual: When creating a Vue app by `npm create vue@latest` and choosing to use Pinia, the app is created with a `counter.ts` file, but that file is not imported anywhere and there is no counter on the web application.

![image](https://github.com/vuejs/create-vue/assets/27309340/00efc638-9f5b-40fa-9357-81ef3ae43081)

![image](https://github.com/vuejs/create-vue/assets/27309340/2b027534-d80e-4b9a-9000-890c05e30053)

![image](https://github.com/vuejs/create-vue/assets/27309340/90862313-5bb2-487a-a701-88f1bd179348)

**Comment by cexbrayat** [comment]
Hi @mterczynski 

Yes, I think it has always been the case, even when it was vuex before pinia, so I suppose this is what @sodatea wanted.

@sodatea Do you think we should use the counter in `HelloWorld.vue` for example? Or does it add too much complexity for not a lot of value?

**Comment by sodatea** [comment]
I would love to, but I couldn't come up a way to include it without making the project template too complex…
