### ISSUE TITLE
How is this different from `npm create vite@latest -- --template vue`?

### ISSUE THREAD

**Issue by rbrtmrtn** [vuejs/create-vue#446]
Hello, and thank you for this helpful scaffolding tool!

I'm wondering if anyone can explain to me how this:

```sh
npm create vue@latest
```

is different from:

```sh
npm create vite@latest -- --template vue
```

Thank you!

**Comment by cexbrayat** [comment]
Hi @rbrtmrtn 

create-vite is maintained by the Vite team and is one of the several templates they offer to quick start a project with various frameworks: https://github.com/vitejs/vite/tree/main/packages/create-vite They are fairly basic project setups.

create-vue is maintained by the Vue team and offers a more complete setup experience as you can pick tools from the ecosystem (unit test, e2e tests, linter, formatted, etc...) and get a state-of-the-art configuration in the end. It uses Vite as well under the hood.

If you want to start a new Vue project, create-vue is the recommended way: https://vuejs.org/guide/quick-start.html#creating-a-vue-application

Hope this helps

**Comment by rbrtmrtn** [comment]
Appreciate this comparison very much @cexbrayat ! Especially this part:

> If you want to start a new Vue project, create-vue is the recommended way

I'll be using `create-vue` in that case 😄
