### ISSUE TITLE
Remove “Vue.vscode-typescript-vue-plugin”

### ISSUE THREAD

**Issue by Yordan-Ramchev** [vuejs/create-vue#455]
### Is your feature request related to a problem? Please describe.
Typescript Vue plugin extension is no longer needed ([#3788](https://github.com/vuejs/language-tools/pull/3788)).

### Describe the solution you'd like
1. Delete **Vue.vscode-typescript-vue-plugin** from **template/base/.vscode/extensions.json**
2. Delete **Vue.vscode-typescript-vue-plugin** related infromation from **utils/generateReadme.ts**
   2.1.` In editors, we need [TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) to make the TypeScript language service aware of `.vue` types.`
   2.2. ` + [TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin)`

### Additional context
https://github.com/vuejs/language-tools/releases/tag/v2.0.0

<img width="443" alt="Screenshot 2024-03-03 at 23 41 00" src="https://github.com/vuejs/create-vue/assets/69005114/f9c37bbb-9277-47c8-a56d-e9186e9df8a0">

---
Can I get an approval to apply these updates?

**Comment by cexbrayat** [comment]
Hi @Yordan-Ramchev 

Good idea, please go ahead 👍
