### ISSUE TITLE
Vite Plugin I Vue DevTools

### ISSUE THREAD

**Issue by Yordan-Ramchev** [vuejs/create-vue#459]
### Is your feature request related to a problem? 

> We provide a Vite plugin for running Vue DevTools. If your project uses Vite, we highly recommend using it as the preferred option for running DevTools, as it offers more powerful features.

https://devtools-next.vuejs.org/guide/vite-plugin#vite-plugin

### Describe the solution
1. Add **vite-plugin-vue-devtools** in **template/base/package.json**
2. Add VueDevTools in **template/base/vite.config.js.data.mjs**
```
{
    id: 'vite-plugin-vue-devtools',
    importer: "import VueDevTools from 'vite-plugin-vue-devtools'",
    initializer: 'VueDevTools()'
}
```
---
Can I get an approval to apply these updates?

**Comment by sodatea** [comment]
That's a great idea!
On a second thought, though, the `devtools-next` project is still under heavy development; it might not be the best time to recommend the project to average users.

So, how about adding it as an "(experimental)" option at the end?

**Comment by Yordan-Ramchev** [comment]
Yeah, that's a reasonable concern/solution.
 
So now the steps that we have to take are:
1. Add another prompt option — _Add VueDevtools extension for debugging? (experimental)_
2. Create **vite.config.js.data.mjs** in **template/config/devtools**
3. Update **snapshot.mjs** with VueDevtools feature flag
4. Update CI script
5. Update locales folder.

Should I proceed with applying these changes?

**Comment by sodatea** [comment]
Yeah, go ahead, please.

**Comment by Yordan-Ramchev** [comment]
PR #460 merged — I'm closing this issue.
