### ISSUE TITLE
How to set up TS configuration to use ES2021 features ?

### ISSUE THREAD

**Issue by liqueurdetoile** [vuejs/create-vue#461]
Hey there,

I'm in trouble with configuring TS through create-vue setup in order to use `Promise.any` ES2021 feature within a vue app. It will be required only on modern browsers, so I can safely use it.

In order to have my IDE (VSCode), Vitest and build step going right through TS check, I have to add `{"compilerOptions": {"lib" : ["ES2022", "DOM"]}}` in `tsconfig.app.json` and remove `{"compilerOptions": {"lib" : []}}` on `tsconfig.vitest.json`.

If I'm not providing `"DOM"`, I have some TS errors for `fetch` or `Blob`.

I'm not used with TS `references` feature but still quite alarmed with the need to remove something in config and add back something that was indeed working before.

Am I doing right or not ?

Thanks

**Comment by cexbrayat** [comment]
Hi @liqueurdetoile 

Can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by liqueurdetoile** [comment]
Thanks for reply @cexbrayat 

By the way, it's an ES2021 feature and not ES2022. I will change the title afterwards.

Here's a [basic setup](https://stackblitz.com/edit/github-gafvek-fa1awn?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts) with a test using `Promise.any` as requested and [this one](https://stackblitz.com/edit/github-gafvek-pejrc7?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts) is the same but with updated TS config. Is it what you're asking for ?

I did some more checks locally. Eventually, the `lib` compiler option empty array in `tsconfig.vitest.json` doesn't need to be removed. I was mistaken by my IDE inertia :

| Lib setup in `tsconfig.app.json` | IDE (VsCode) | Vitest | Dev server | Build
|-|-|-|-|-|
|Default (none)| error TS2550 | OK | OK | error TS2550
|Only `"lib": "[ES2021]"`| OK | OK | OK | error TS2304 on `fetch` and `Blob`
|`"lib": "[ES2021, DOM]"`|OK|OK|OK|OK

On stackblitz, IDE error seems to persist with updated config.

I have no extra vite/vitest config except `vite-plugin-vuetify` and `vite-plugin-circular-dependency` plugins and a basic setup for dev server to proxy api and assets calls.

**Comment by cexbrayat** [comment]
Yes, that makes sense. As you can see in the base tsconfig here https://github.com/vuejs/tsconfig/blob/22e15e3947c8ce1d9c5992229da0351c464fb9e8/tsconfig.dom.json#L4-L15, the default lib includes `ES2020`, 'dom`, and `dom.iterable`. if you want to override it, then you can use `ES2021`, 'dom`, and `dom.iterable` 👍

**Comment by liqueurdetoile** [comment]
Thanks !
I was a bit confused between all config files 😕
