### ISSUE TITLE
regression: flags are not interpreted correctly in v3.10 when creating project

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/create-vue#464]
```
npm create vue@3.10.0 --yes -- --typescript repro
```

creates a `--typescript` directory whereas:

```
npm create vue@3.9.2 --yes -- --typescript repro
```

creates a `repro` directory (as expected).

Maybe this is due to https://github.com/vuejs/create-vue/pull/443 and the introduction of minimist? cc @Yordan-Ramchev

**Comment by Yordan-Ramchev** [comment]
Maybe it's introduced in `let targetDir = args[0]`. I will take a look into it.
