### ISSUE TITLE
cannot find module using @ absolute path syntax Visual Studio Code

### ISSUE THREAD

**Issue by freeany** [vuejs/create-vue#465]
I used pnpm create vue@latest to create a vue project and opened it with vscode. 
vscode has installed the latest version of vue-office. 
You have configured tsconfig.app.json with `"@": ["./src/*" ]`
'@' has also been configured in vite.config.ts: `'@': fileURLToPath(new URL('./src', import.meta.url))`
 but when I use the @ alias,
 it prompts `Cannot find module '@/utils/cache' or its corresponding type declarations.ts-plugin(2307)`

<img width="1094" alt="image" src="https://github.com/vuejs/create-vue/assets/47732430/33fa43e7-7d40-49f6-aafc-6d7ad86d0a77">

<img width="1204" alt="image" src="https://github.com/vuejs/create-vue/assets/47732430/f0fb3126-577d-4da0-b250-6f5e06b9c06e">

<img width="1338" alt="image" src="https://github.com/vuejs/create-vue/assets/47732430/ec31babe-88ce-4c0d-90a8-b8aa4d7d22a1">

**Comment by cexbrayat** [comment]
Hi @freeany 

Do you have an error when you run `npm run type-check`? If not, then it means this is just an issue with VS Code, and sometimes it goes away when restarting the IDE (or TS server).

**Comment by freeany** [comment]
> Hi @freeany
> 
> Do you have an error when you run `npm run type-check`? If not, then it means this is just an issue with VS Code, and sometimes it goes away when restarting the IDE (or TS server).

npm run type-check is error
<img width="1076" alt="image" src="https://github.com/vuejs/create-vue/assets/47732430/9426f27f-519c-4782-9162-22272294d366">

This is vite.config.ts
<img width="1256" alt="image" src="https://github.com/vuejs/create-vue/assets/47732430/f16d1047-e581-4599-90a5-7348d8e0944c">

**Comment by cexbrayat** [comment]
That's weird indeed.

Can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by freeany** [comment]
> That's weird indeed.
> 
> Can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ?
> 
> It only takes a few minutes, and we'll be able to take a look

I found the cause of the error, a low-level mistake that belongs to me。
Correct configuration：
```ts
  "paths": {
        "@/*": ["./src/*"]
   }
```


I don’t know how to configure it like this：
```ts
  "paths": {
    "@": ["./src/*"]
  }
```

I'm very sorry.

**Comment by cexbrayat** [comment]
No worries, let's close the issue then.
