### ISSUE TITLE
Add ESLint run-on-save VSCode settings

### ISSUE THREAD

**Issue by yoshi-pi** [vuejs/create-vue#466]
As of #442, settings.json is now added when picking Prettier. How about adding the following setting when picking ESLint as well, so that linting is done on save?
```
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "explicit"
  }
}
```

**Related Issue**
#302

**Comment by cexbrayat** [comment]
Hi @yoshi-pi 

Yes, I think this would be a good idea.
Would you like to open a PR for this? We would gladly review and merge it.

**Comment by yoshi-pi** [comment]
@cexbrayat I have opened a PR.

**Comment by sodatea** [comment]
Released
