### ISSUE TITLE
TS2307: Cannot find module '@/components/echarts' or its corresponding type declarations.

### ISSUE THREAD

**Issue by freeany** [vuejs/create-vue#473]
I have installed the latest version of Vue - Official v2.0.7, the vscode version is the latest, my code is opened in vscode, everything is displayed perfectly, no errors are reported, and you can also click on the corresponding module with the mouse, but I got a lot of errors when I ran `npm run type-check`. I was confused and didn’t know the reason.

### version

-  vue-tsc: 1.8.27
-  typescript: @5.3.3

### `npm run type-check`
-  ` "type-check": "vue-tsc --build --force --traceResolution",`

<img width="1412" alt="image" src="https://github.com/vuejs/language-tools/assets/47732430/0914abf9-d975-4cf8-8b19-a0a776dd6f10">

**Comment by Yordan-Ramchev** [comment]
I don't think it's **create-vue** related issue.

My assumption based on the log is that you can update tsconfig.json — https://www.typescriptlang.org/tsconfig#include
There you can `include` all the ts stuff that's in types folder.

**Comment by freeany** [comment]
> I don't think it's **create-vue** related issue.
> 
> My assumption based on the log is that you can update tsconfig.json — https://www.typescriptlang.org/tsconfig#include There you can `include` all the ts stuff that's in types folder.


Thank you for your reply. My tsconfig.json was automatically created for me after pnpm create vue@latest. This is its configuration:
<img width="663" alt="image" src="https://github.com/vuejs/create-vue/assets/47732430/9d57a34c-4271-441e-8133-f30bc9b93e81">

<img width="1041" alt="image" src="https://github.com/vuejs/create-vue/assets/47732430/8bf0b482-9e9a-4dae-b9ce-e7349778f735">

And can't find moudle dom api 
<img width="787" alt="image" src="https://github.com/vuejs/create-vue/assets/47732430/38b83218-5ef9-4d27-af9f-ebcabd4ca571">

**Comment by Yordan-Ramchev** [comment]
Try in ts.app.config.json in **include** array something like “types/**.d.ts” (adjust it base on the files that you have there) this may fix the stuff below.
<img width="738" alt="Screenshot 2024-03-20 at 13 30 00" src="https://github.com/vuejs/create-vue/assets/69005114/34f0e386-40a0-4512-a367-11f0adef2843">

**Comment by freeany** [comment]
I replaced all the configurations in tsconfig.json with the configurations in tsconfig.app.json, and the execution was normal.

<img width="986" alt="image" src="https://github.com/vuejs/create-vue/assets/47732430/6cc1b468-700c-4494-88d1-eefe0cfff2cd">


I don’t know why I need to distinguish between tsconfig.app.json and tsconfig.node.json when I use `pnpm create vue@latest` to create a vue project, and then use references to reference tsconfig.node.json and tsconfig.app.json , what is the significance of doing this? what is the benefit? Why make a distinction? I'm full of doubts 🤔️

**Comment by Yordan-Ramchev** [comment]
Each configuration file can focus on a specific aspect of the project:
1. **tsconfig.node.json** extends the tsconfig.json and is specifically tailored for Node.js environments. The inclusion of vite.config.ts in the include array of tsconfig.node.json is notable because it ensures that the TypeScript compiler is aware of this file and its types when compiling the project. This setup is crucial for projects that use Vite, as it allows for the correct handling of the Vite configuration file within a Node.js context
2.  **tsconfig.app.json** suggests a further division of the TypeScript configuration for different parts of the application. This could be used to specify configurations that are specific to the application, allowing for more granular control over the TypeScript compilation process.

https://stackoverflow.com/questions/72027949/why-does-vite-create-two-typescript-config-files-tsconfig-json-and-tsconfig-nod

**Comment by freeany** [comment]
> Each configuration file can focus on a specific aspect of the project:
> 
> 1. **tsconfig.node.json** extends the tsconfig.json and is specifically tailored for Node.js environments. The inclusion of vite.config.ts in the include array of tsconfig.node.json is notable because it ensures that the TypeScript compiler is aware of this file and its types when compiling the project. This setup is crucial for projects that use Vite, as it allows for the correct handling of the Vite configuration file within a Node.js context
> 2. **tsconfig.app.json** suggests a further division of the TypeScript configuration for different parts of the application. This could be used to specify configurations that are specific to the application, allowing for more granular control over the TypeScript compilation process.
> 
> https://stackoverflow.com/questions/72027949/why-does-vite-create-two-typescript-config-files-tsconfig-json-and-tsconfig-nod

Thank you very much for your reply and answer!  I read the relevant content of the link carefully. I guess the bug I just encountered is due to a problem with vue-tsc, which did not recognize tsconfig.app.json.

**Comment by freeany** [comment]
> FYI — latest vue-tsc version is 2.0.7
> 
> And I am glad that you've resolved this issue. Feel free to close it. :)

I upgraded vue-tsc to the latest version, and then changed the "type-check" script to: "vue-tsc --noEmit -p tsconfig.app.json". solved this problem. thanks
