### ISSUE TITLE
Cannot find module './App.vue' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by imxue** [vuejs/create-vue#48]
Does this warning need to add  shims-vue.d.ts  files to eliminate it?
```Ts 
declare module '*.vue' {   
   import type { DefineComponent } from 'vue'   
   const component: DefineComponent<{}, {}, any>   
   export default component 
}
```

**Comment by sodatea** [comment]
Install *TypeScript Vue Plugin (Volar)* or enable *take-over mode*. The instructions are already included in the generated README.md.

https://github.com/vuejs/create-vue/blob/e3ea96db27feca7ad0d04f8f1b79f2d58c56dfc8/utils/generateReadme.js#L7-L16
