### ISSUE TITLE
Cannot find base config file "@vue/tsconfig/tsconfig.dom.json" [tsconfig.json]

### ISSUE THREAD

**Issue by cnese** [vuejs/create-vue#485]
![image](https://github.com/vuejs/create-vue/assets/12219853/78c99e58-b109-489b-8f99-962505fe2401)
"dependencies": {
"vue": "^3.4.21"
},
"devDependencies": {
"@vitejs/plugin-vue": "^5.0.4",
"@vue/tsconfig": "^0.5.1",
"typescript": "^5.2.2",
"vite": "^5.2.0",
"vue-tsc": "^2.0.6"
}

**Comment by Yordan-Ramchev** [comment]
@cnese My assumption is that you are trying to run `create-vue` with only Typescript option. If that's the case — can you compare `package.json` with the one running in stackblitz? 
Here is a link — https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript?file=README.md
It's using the build from playground - https://github.com/vuejs/create-vue-templates/tree/5ac3a87a75066171cbfa3e545e7f13428ae459e9/typescript

**Comment by cnese** [comment]
Create with **npm vue@latest** After creating a new project, this warning will appear when starting the project with **npm run dev**.

**Comment by Yordan-Ramchev** [comment]
I could not reproduce it. 
I am running `npm create vue@latest` with these options creates a different version of the packages used in package.json
<img width="505" alt="Screenshot 2024-04-04 at 20 15 02" src="https://github.com/vuejs/create-vue/assets/69005114/bf19f773-3169-4e5d-92e4-ed4a421551e3">
Here is a list with `devDependencies` that are generated (they are different than yours):
```
  "devDependencies": {
    "@tsconfig/node20": "^20.1.2",
    "@types/node": "^20.11.28",
    "@vitejs/plugin-vue": "^5.0.4",
    "@vue/tsconfig": "^0.5.1",
    "npm-run-all2": "^6.1.2",
    "typescript": "~5.4.0",
    "vite": "^5.1.6",
    "vue-tsc": "^2.0.6"
  }
```
Tested with node `v18.18.1` & `v16.20.2`

--- 

Can you reproduce your issue in https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript?file=env.d.ts

**Comment by cnese** [comment]
![image](https://github.com/vuejs/create-vue/assets/12219853/cf22c29e-457e-4027-867e-3521da8e1a47)
![image](https://github.com/vuejs/create-vue/assets/12219853/cd362dce-bda8-4a73-bbb3-f0d4eb055c6e)
**Stackblitz.com** will not display this warning

**Comment by cexbrayat** [comment]
Have you tried to delete the node modules directory and run npm install again?

**Comment by cnese** [comment]
Yes, I have also recreated multiple projects.

**Comment by cexbrayat** [comment]
And can you see the file mentioned in the warning in your node modules?

**Comment by cnese** [comment]
You can see the file
![image](https://github.com/vuejs/create-vue/assets/12219853/006ef061-6612-494b-bd4b-faec4ec30ea1)
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "lib": [
      // Target ES2020 to align with Vite.
      // <https://vitejs.dev/config/build-options.html#build-target>
      // Support for newer versions of language built-ins are
      // left for the users to include, because that would require:
      //   - either the project doesn't need to support older versions of browsers;
      //   - or the project has properly included the necessary polyfills.
      "ES2020",

      "DOM",
      "DOM.Iterable"

      // No `ScriptHost` because Vue 3 dropped support for IE
    ],

    // Set to empty to avoid accidental inclusion of unwanted types
    "types": []
  }
}

**Comment by cexbrayat** [comment]
Can you share your project on GitHub? We'll check if we have the same issue

**Comment by cnese** [comment]
OK，Submitted to GitHub: **https://github.com/cnese/vite**

**Comment by Yordan-Ramchev** [comment]
If we compare **tsconfig** files:
These are yours, and the files that are generated are different than they are supposed to.
<img width="810" alt="Screenshot 2024-04-05 at 9 47 48" src="https://github.com/vuejs/create-vue/assets/69005114/94e473b2-2aa1-4085-803c-0c88b8296480">

They should look like this:
<img width="843" alt="Screenshot 2024-04-05 at 9 48 55" src="https://github.com/vuejs/create-vue/assets/69005114/76bb70b2-9bb6-49c1-8c47-9dc1fe0230e9">

What command are you running in the terminal, what package manager do you use and what version?
(the scaffold is a lot different from it should be)

**Comment by cnese** [comment]
What command did you use to create this project?

**Comment by cnese** [comment]
![image](https://github.com/vuejs/create-vue/assets/12219853/48278199-1c91-4820-9786-b73aa8b04a60)
![image](https://github.com/vuejs/create-vue/assets/12219853/eef76fa2-aee3-434b-9bc1-a0c0a4dce1e4)

**Comment by cexbrayat** [comment]
Ok so you're not using create-vue, you're using create-vite which is a different project. You can open an issue there https://github.com/vitejs/vite/tree/main if you want to.

We recommend that you follow https://github.com/vuejs/create-vue?tab=readme-ov-file#usage to use create-vue
