### ISSUE TITLE
ESLint v9 support

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/create-vue#488]
ESLint v9 has been released and we'll need to change a few things to properly support it.

`npm run lint` currently fails to run with eslint v9:
```
❯ npm run lint

> eslint-with-prettier@0.0.0 lint
> eslint . --ext .vue,.js,.jsx,.cjs,.mjs --fix --ignore-path .gitignore

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
```

We'll also probably need to migrate the configuration file to use the flat config format:
- https://eslint.org/docs/latest/use/configure/migration-guide

**Comment by JoostKersjes** [comment]
See #451 for supporting the new default "Flat Config Files".

**Comment by jez9999** [comment]
I'd definitely like to see the project scaffolds using the flat config format ASAP.  It greatly reduces the complexity of configuring ESLint, as well as setting a bunch of reasonable defaults the old system didn't and organizing things better.

**Comment by lovetingyuan** [comment]
+1 @sodatea

**Comment by ayu-exorcist** [comment]
Maybe [eslint-config](https://github.com/antfu/eslint-config) is another option.

**Comment by benoit74** [comment]
I would love to see this land at some point. I failed to do the update on my project despite typescript-eslint 8 being released a long time ago

**Comment by BabyLy233** [comment]
Also looking forward to supporting ESLint v9 so that we can use flat config

**Comment by ascott18** [comment]
A brand new Vue project comes with all these deprecation warnings, which doesn't feel like a very nice welcome to users who might be new to Vue. All of these are dependencies of eslint.

![image](https://github.com/user-attachments/assets/7c42184c-57ee-4885-be8a-916f17ce786e)

Are there any core maintainers working on this? And if not, what can the community do to help out? It seems like the problems are spread out across multiple projects and multiple repos, which makes it hard to know where to start for someone looking to help out.

**Comment by JoseGoncalves** [comment]
I find a bit strange that 5 months after the release of ESLint v9 there is still no "official" way to scaffold a Vue project supporting it. Can the community help in any way to push this forward?

**Comment by messenjer** [comment]
ESLint v8.x end of life is October 5, 2024 : https://eslint.org/blog/2024/09/eslint-v8-eol-version-support/

**Comment by haoqunjiang** [comment]
I've been taking a break for most of the past few months due to burnout.

But now that ESLint 8 is about to hit EOL, I've put together a basic plan for minimum ESLint 9 support. You can check it out here: https://github.com/vuejs/eslint-config-typescript/pull/81. I hope it helps.

**Comment by JoseGoncalves** [comment]
Hi @haoqunjiang. Does that mean that there will be no Javascript support for ESLint v9, only Typescript?

**Comment by haoqunjiang** [comment]
> Hi @haoqunjiang. Does that mean that there will be no Javascript support for ESLint v9, only Typescript?

You don't need any new config package for JavaScript.
I would update `@vue/create-eslint-config` to create a new boilerplate configuration file to support that.

Here's my current configuration file for a minimal JavaScript Vue Project:

```js
import js from '@eslint/js'
import pluginVue from 'eslint-plugin-vue'

export default [
  // > config objects that don’t specify files or ignores apply to all files that have been matched by any other configuration object
  // So we specify here once and the following extends will all apply to the same files
  {
    files: [
      '**/*.js',
      '**/*.mjs',
      '**/*.jsx',
      '**/*.vue'
      // default sourceType is set to 'module' so we don't support .cjs files
    ],
    ignores: [
      // node_modules & .git are ignored by default
      '**/dist/**',
      '**/dist-ssr/**',
      '**/coverage/**'
    ]
  },
  js.configs.recommended,
  ...pluginVue.configs['flat/essential']
]
```

**Comment by benoit74** [comment]
> I've been taking a break for most of the past few months due to burnout.

Take care!

**Comment by JoseGoncalves** [comment]
> You don't need any new config package for JavaScript.

If I one wants to use prettier along with eslint it will need updates in `@vue/eslint-config-prettier`. It seems that PR https://github.com/vuejs/eslint-config-prettier/pull/22 addresses that, wright?
