### ISSUE TITLE
typescript .vue file include @types/node when include some package

### ISSUE THREAD

**Issue by ZurrTum** [vuejs/create-vue#500]
### Describe the bug

When I introduce certain packages, for example: socket.io-client
Or vite in the picture
setTimeout return NodeJS.Timeout
![image](https://github.com/vuejs/create-vue/assets/31088040/0d33cb6b-5738-476d-81be-f34b6b8f6b1f)

### Expected behavior

setTimeout return number
![image](https://github.com/vuejs/create-vue/assets/31088040/fd90efc6-00bd-466f-a4f6-fb9e4b40e3fb)

### How to reproduce
1. `npm create vue@latest`
2. typescript yes
3. `cd vue-project && npm install`
4. using vscode open App.vue
5. check setTimeout return type is number
6. import some package e.g.: vite
7. check setTimeout return type is NodeJS.Timeout

## tsconfig.json (default)
```json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    }
  ]
}
```
## tsconfig.app.json (default)
```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",

    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

**Comment by cexbrayat** [comment]
Hi @ZurrTum 

I don't think this is an issue with create-vue. If you're using https://github.com/vuejs/language-tools you can maybe open an issue there with a reproduction and check if this is not an issue with the VS Code extension.

**Comment by ZurrTum** [comment]
Supplement, if anyone encounters:
`/// <reference types="node" />`
[Node module dependencies that use a triple-slash directive to reference libs poison the global scope  #33111](https://github.com/microsoft/TypeScript/issues/33111)

### Imperfect solution
tsconfig.app.json only, include vite.config.ts, declare node:url
#### env.d.ts
```ts
/// <reference types="vite/client" />
declare module "node:url" {
  class URL {
    constructor(
      input: string | { toString: () => string },
      base?: string | URL
    );
  }
  function fileURLToPath(url: string | URL): string;
}
```
