### ISSUE TITLE
升级vue3小版本后 切换路由页面空白，控制台报错！

### ISSUE THREAD

**Issue by fwd001** [vuejs/create-vue#501]
### Describe the bug

![image](https://github.com/vuejs/create-vue/assets/32030418/3d8adb18-0ae3-4bc3-a54a-58ab493dd00b)
我的生成环境ci 会删除lock文件重新安装依赖，今天白天发现 发布后切换路由会页面空白，控制台报错，添加上一版本的lock文件后就好了，请查看解决
![image](https://github.com/vuejs/create-vue/assets/32030418/f1b65f14-969b-4f0b-9b3c-1998eca09a3a)

**Comment by fwd001** [comment]
![image](https://github.com/vuejs/create-vue/assets/32030418/8a0d7571-0376-4ee5-923a-454a795d15a9)
用另一个项目试了 ，npm run build && vite preview 可复现， pnpm vite 没问题

**Comment by cexbrayat** [comment]
Hi @fwd001 

I don't think this is an issue with create-vue which is just a project generator.
You should try to isolate which dependency update produces the error and then you'll probably be able to resolve your issue.
