### ISSUE TITLE
Update README screenshot

### ISSUE THREAD

**Issue by btea** [vuejs/create-vue#503]
### Describe the bug

![image](https://github.com/vuejs/create-vue/assets/24516654/7ad39916-2feb-433b-901d-b67a49545127)
When creating a project, a new option is added to whether to add `devtools`, and the screenshots in `README` should be updated.

**Comment by Yordan-Ramchev** [comment]
May I suggest adding that Vue 2 is EOL, something like:

## Usage

```sh
npm create vue@latest
```

> [!NOTE]
>  (`@latest` or `@legacy`) MUST NOT be omitted, otherwise `npm` may resolve to a cached and outdated version of the package.

Or, if you need to support IE11, you can create a Vue 2 project with:

```sh
npm create vue@legacy
```

> [!IMPORTANT]
> [Vue 2 Has Reached End of Life](https://v2.vuejs.org/eol/)

**Comment by btea** [comment]
I think that's great, what do you think? @cexbrayat

**Comment by cexbrayat** [comment]
Yes, it's a good idea 👍
