### ISSUE TITLE
About `tsBuildInfoFile` config

### ISSUE THREAD

**Issue by btea** [vuejs/create-vue#516]
I initialized a project using pinia. When I declare a reference to a component in `defineStore`, ts will error and give the following prompt.

![image](https://github.com/vuejs/create-vue/assets/24516654/edb3d376-0948-4669-981b-b95836a263e4)

After I delete the `tsBuildInfoFile` related configuration, the code will not go wrong. 

![image](https://github.com/vuejs/create-vue/assets/24516654/6733b881-2516-4462-9ec1-e430ddbc34f1)

I'm not sure why? 🤔

**Comment by cexbrayat** [comment]
I think this is a TS issue. There is a long thread on the TS repo, maybe you can find a solution there https://github.com/microsoft/TypeScript/issues/47663 When I encountered this, I typed the variable (your `useCounterStore`) to make it go away IIRC

**Comment by btea** [comment]
@cexbrayat Thank you for your detailed answer. 👍
