### ISSUE TITLE
Support githooks like husky or yorkie

### ISSUE THREAD

**Issue by sunsunmonkey** [vuejs/create-vue#519]
### Please describe

Do we have the plan for support githooks like husky or yorkie?

**Comment by Yordan-Ramchev** [comment]
_Personal opinion_ — no need to introduce additional complexity to **create-vue**. Initializing husky in a project is really easy, just running a single command at the root of the project `npx husky init` (recommended) > https://typicode.github.io/husky/get-started.html#husky-init-recommended

Other related issues: 
1. #167 
2. #164

**Comment by sunsunmonkey** [comment]
ok，I get it. Thank you.
