### ISSUE TITLE
[playground templates] Add devtools-router-pinia

### ISSUE THREAD

**Issue by Yordan-Ramchev** [vuejs/create-vue#522]
### Please describe
Update existing `devtools` to `devtools-router-pinia` or add additional `devtools-router-pinia` playground template.

### Additional context
The goal is to update or add playground link to `devtools-router-pinia` in https://devtools-next.vuejs.org/ so it can showcase more DevTools features.

Can I get an approval to proceed?

**Comment by cexbrayat** [comment]
Sounds good to me 👍
