### ISSUE TITLE
npm init vue@latest project fails to run

### ISSUE THREAD

**Issue by aner-perez** [vuejs/create-vue#53]
When trying to create a new Vue 3 project using `npm init vue@latest` with the defaults selected, I get a `Cannot read property 'split' of undefined` error when trying to run the project.  See output below:

> $ **npm init vue@latest**
> npx: installed 1 in 1.371s
> 
> Vue.js - The Progressive JavaScript Framework
> 
> ✔ Project name: … vue-defaults
> ✔ Add TypeScript? … No / Yes
> ✔ Add JSX Support? … No / Yes
> ✔ Add Vue Router for Single Page Application development? … No / Yes
> ✔ Add Pinia for state management? … No / Yes
> ✔ Add Vitest for Unit Testing? … No / Yes
> ✔ Add Cypress for both Unit and End-to-End testing? … No / Yes
> ✔ Add ESLint for code quality? … No / Yes
> 
> Scaffolding project in /home/aner/vue-defaults...
> 
> Done. Now run:
> 
>   cd vue-defaults
>   npm install
>   npm run dev
> 
> $ **cd vue-defaults**
> $ **npm install**
> 
> > esbuild@0.14.21 postinstall /home/aner/vue-defaults/node_modules/esbuild
> > node install.js
> 
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/vite/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.14.21 (node_modules/esbuild/node_modules/esbuild-android-arm64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.14.21: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.14.21 (node_modules/esbuild/node_modules/esbuild-darwin-arm64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.14.21: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-64@0.14.21 (node_modules/esbuild/node_modules/esbuild-darwin-64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-64@0.14.21: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.14.21 (node_modules/esbuild/node_modules/esbuild-freebsd-arm64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.14.21: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.14.21 (node_modules/esbuild/node_modules/esbuild-linux-32):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.14.21: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.14.21 (node_modules/esbuild/node_modules/esbuild-linux-mips64le):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.14.21: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.14.21 (node_modules/esbuild/node_modules/esbuild-linux-arm64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.14.21: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.14.21 (node_modules/esbuild/node_modules/esbuild-freebsd-64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.14.21: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.14.21 (node_modules/esbuild/node_modules/esbuild-linux-arm):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.14.21: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.14.21 (node_modules/esbuild/node_modules/esbuild-linux-ppc64le):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.14.21: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-s390x@0.14.21 (node_modules/esbuild/node_modules/esbuild-linux-s390x):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-s390x@0.14.21: wanted {"os":"linux","arch":"s390x"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-riscv64@0.14.21 (node_modules/esbuild/node_modules/esbuild-linux-riscv64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-riscv64@0.14.21: wanted {"os":"linux","arch":"riscv64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.14.21 (node_modules/esbuild/node_modules/esbuild-openbsd-64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.14.21: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.14.21 (node_modules/esbuild/node_modules/esbuild-netbsd-64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.14.21: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.14.21 (node_modules/esbuild/node_modules/esbuild-sunos-64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.14.21: wanted {"os":"sunos","arch":"x64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.14.21 (node_modules/esbuild/node_modules/esbuild-windows-32):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.14.21: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-64@0.14.21 (node_modules/esbuild/node_modules/esbuild-windows-64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-64@0.14.21: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.14.21 (node_modules/esbuild/node_modules/esbuild-windows-arm64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.14.21: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
> npm WARN vue-defaults@0.0.0 No repository field.
> npm WARN vue-defaults@0.0.0 No license field.
> 
> added 32 packages from 51 contributors and audited 51 packages in 2.642s
> 
> 4 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> $ **npm run dev**
> 
> > vue-defaults@0.0.0 dev /home/aner//vue-defaults
> > vite
> 
> error when starting dev server:
> TypeError: Cannot read property 'split' of undefined
>     at /home/aner/vue-defaults/node_modules/vite/dist/node/chunks/dep-1412e872.js:70782:33
>     at Array.reduce (<anonymous>)
>     at _interpolate (/home/aner/vue-defaults/node_modules/vite/dist/node/chunks/dep-1412e872.js:70768:18)
>     at expand (/home/aner/vue-defaults/node_modules/vite/dist/node/chunks/dep-1412e872.js:70812:32)
>     at loadEnv (/home/aner/vue-defaults/node_modules/vite/dist/node/chunks/dep-1412e872.js:71436:13)
>     at resolveConfig (/home/aner/vue-defaults/node_modules/vite/dist/node/chunks/dep-1412e872.js:70919:9)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async createServer (/home/aner/vue-defaults/node_modules/vite/dist/node/chunks/dep-1412e872.js:56404:20)
>     at async CAC.<anonymous> (/home/aner/vue-defaults/node_modules/vite/dist/node/cli.js:688:24)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! vue-defaults@0.0.0 dev: `vite`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the vue-defaults@0.0.0 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/aner/.npm/_logs/2022-02-11T19_59_42_034Z-debug.log
>

**Comment by sodatea** [comment]
Can't reproduce.

1. Do you have a reproduction repo?
2. The error is thrown from the `dotenv-expand` dependency. Please check if there's any irregular syntax in your `.env.*` files in the project, or in any ancestor directories.

**Comment by aner-perez** [comment]
Thanks for the quick reply, looks like the problem is with the **"or in any ancestor directories"** part of your answer.

I am running on a Linux system so I have a ".env" file in my home directory that is used by the shell (as has always been done in Unix systems).  If I rename my $HOME/.env to $HOME/.tmp.env then I am able to run the dev server successfully.

If the project created by create-vue is going to recursively look up the directory structure for a file called `.env*`,  then it should place a default .env file in the generated project so it does not go looking up the directory hierarchy to find a random unrelated file called .env*  I tried creating an empty .env in the project folder and that seemed to also fix the issue.

As it stands, many Linux users will run into this issue and not know how to address it.
