### ISSUE TITLE
 Projects must list all files or use an 'include' pattern.ts(6307)

### ISSUE THREAD

**Issue by paparent** [vuejs/create-vue#55]
Hi! 

I'm trying to get unit tests to work properly and don't know how to deal with the following situation:

I started a new project with `npm init vue@3` like so:

✔ Add TypeScript? … No / **Yes**
✔ Add JSX Support? … **No** / Yes
✔ Add Vue Router for Single Page Application development? … **No** / Yes
✔ Add Pinia for state management? … **No** / Yes
✔ Add Vitest for Unit Testing? … No / **Yes**
✔ Add Cypress for End-to-End testing? … **No** / Yes
✔ Add ESLint for code quality? … No / **Yes**
✔ Add Prettier for code formatting? … **No** / Yes

At root of the `src` folder I add a simple TS file:

```ts
export const add = (a: number, b: number) => a + b;
```

And in my test, when I import it:

```ts
import { add } from '../utils';
```

I get the following error message:

```
module "...../src/utils"
File '..../src/utils.ts' is not listed within the file list of project '..../tsconfig.vitest.json'. Projects must list all files or use an 'include' pattern.ts(6307)
```

I left the tsconfigs file untouched, but here there are:
```
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },

  "references": [
    {
      "path": "./tsconfig.vite-config.json"
    },
    {
      "path": "./tsconfig.vitest.json"
    }
  ]
}
```

```
{
  "extends": "@vue/tsconfig/tsconfig.node.json",
  "include": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "types": ["node", "jsdom"]
  }
}
```

**Comment by sodatea** [comment]
What's the path of your test file?

**Comment by paparent** [comment]
> What's the path of your test file?

test file is in `src/__tests__/utils.test.ts`, and tested file is `src/utils.ts`.

**Comment by sodatea** [comment]
Opened a PR for this: #56

Thank you so much for the report! It's a huge oversight on my part.

**Comment by paparent** [comment]
@sodatea  no worries! I'm starting a brand new project. So I either open issues here and there or PRs when I know how to fix them!
