### ISSUE TITLE
component lifecycle

### ISSUE THREAD

**Issue by chinaSoftMobile** [vuejs/create-vue#595]
Can we add a feature that allows the parent component to obtain the child component lifecycle function, and the parent component can do some things during the child component lifecycle

**Comment by cexbrayat** [comment]
@chinaSoftMobile This is not the repository for this issue: this repo is `create-vue` which generats the skeleton of a Vue project. The framework itself is https://github.com/vuejs/core

But you should probably ask your question on Discord first https://discord.com/invite/vue before asking for a new feature
