### ISSUE TITLE
Consider adding max_line_length = 100 to .editorconfig

### ISSUE THREAD

**Issue by segevfiner** [vuejs/create-vue#598]
The `.pretteirrc.json` generated by previous versions included `"printWidth": 100`, so the removal of this causes massive reformatting of files.

**Comment by cexbrayat** [comment]
hi @segevfiner 

I think this has already been fixed in https://github.com/vuejs/create-eslint-config/commit/5c931554667df70f7b551e8a53de65bfd3d50dc5 
It should be included in the next release of create-vue

**Comment by segevfiner** [comment]
Yeah. I noticed just a few seconds before you closed this :P
