### ISSUE TITLE
Language attribute of <html> element should not be set to English by default

### ISSUE THREAD

**Issue by botic** [vuejs/create-vue#599]
The current HTML template explictly sets the language attribute to English with `lang="en"`. This turned out to be a bad pattern if your project is not solely targeting the English-speaking communities. Google Chrome might auto-translate such pages, even if the actual language of the text is in German.

See more details here: https://github.com/vuejs/vue-cli/issues/5945

If not changed, Vite-powered Vue projects will see a high number of false language attributes in the wild!

[Code search returned](https://github.com/search?q=repo%3Avuejs%2Fcreate-vue%20lang%3D%22en%22&type=code) two places with explicit language attribute:

- [template/base/index.html](https://github.com/vuejs/create-vue/blob/bf5d533313301b74c87bd6ef2103ab5daf50eaac/template/base/index.html#L2)
- [template/config/nightwatch-ct/nightwatch/index.html](https://github.com/vuejs/create-vue/blob/bf5d533313301b74c87bd6ef2103ab5daf50eaac/template/config/nightwatch-ct/nightwatch/index.html#L2)

### Expected behavior

The language attribute on the element of the template should be absent or empty. This will let the user agent decide (e.g. autodetect) the language of the page.

You can find the vue-cli solution here: https://github.com/vuejs/vue-cli/commit/2373df16302d188afee65bfa6b3f475e1e739dfe

### How to reproduce

Just create a new project :-)

**Comment by cexbrayat** [comment]
Hi @botic 

Sure, feel free to open a PR to fix this 👍

**Comment by botic** [comment]
> Sure, feel free to open a PR to fix this 👍

Sorry, now included. The Nightwatch template should be irrelevant, so it's just the `base/index.html`
