### ISSUE TITLE
Jest support

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/create-vue#6]
Currently, create-vue creates a project with cypress-ct as the unit testing solution.
Some of the rationales are explained by @yyx990803 [in this video](https://youtu.be/gpTbH469Qog?t=3589)

As much as we all love Cypress, Jest is a very popular solution in the unit testing world.

Would it be possible to have the choice to use Jest at the project creation?

That would be a tremendous help to teams who want to migrate existing projects. I understand that Jest + Vite is complicated at the moment, but the issue is already really popular https://github.com/vitejs/vite/issues/1955
Even if we can't leverage Vite with jest, maybe we can offer a simple setup using Jest + `@vue/vue3-jest` + VTU as the CLI does?

If the team is willing to add Jest support out-of-the-box, I can work on a PR to add this.

**Comment by sodatea** [comment]
Now that we have added Vitest support out of the box, I don't think we are gonna add Jest to this package.
So I'm closing this issue.
