### ISSUE TITLE
oxlint lint node_modules with default configuration

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/create-vue#604]
### Describe the bug

With v3.12, a project created with the experimental oxlint support will throw when run `npm run lint` because oxlint lint the node_modules of the project.

### Expected behavior

`npm run lint` shouldn't error in a new project.

It would be great to add a flag to generate a project with oxlint (`--oxlint` ? `--oxlint-experimental`?).
It would also be great to add a step on the CI to build a project with such a flag, and be able to catch issues like this one.

**Comment by haoqunjiang** [comment]
But I can't reproduce it:
<img width="556" alt="image" src="https://github.com/user-attachments/assets/d9d5acc6-81d2-41ab-a714-3e92bfea886b">

**Comment by cexbrayat** [comment]
I used npm, maybe it makes a difference?

**Comment by haoqunjiang** [comment]
Ah, I think so.

Oxlint uses the [`ignore` crate](https://crates.io/crates/ignore), which ignores hidden files and directories (those start with `.`) by default. PNPM installs dependencies under `node_modules/.pnpm` and then creates symlinks to them. So, the actual dependencies are in an ignored directory; therefore, there are no errors.
