### ISSUE TITLE
Lint and Format with @biomejs/biome

### ISSUE THREAD

**Issue by Coinhexa** [vuejs/create-vue#608]
### Please describe

[@biomejs/biome](https://biomejs.dev/) does both formatting and linting without the quirks of eslint and prettier and in a much faster manner. Let devs choose biome as an opton instead of ESLint and Prettier?

### Additional context

<img width="366" alt="image" src="https://github.com/user-attachments/assets/6c3f8107-b552-45a9-ad55-4a0ea9e1a669">

**Comment by cexbrayat** [comment]
Hi @Coinhexa 

We recently released the experimental support of oxlint, which is an alternative to biome (rust based as well).
I don't think we'll support every linting/formatting tool though, as the cost of maintenance is quite heavy.

You can already give a try to oxlint, see https://github.com/vuejs/create-vue/releases/tag/v3.12.0
Let us know if you like it!
