### ISSUE TITLE
Build command in generated README.md does not work with Bun

### ISSUE THREAD

**Issue by Hornwitser** [vuejs/create-vue#614]
### Describe the bug

When creating a project using `bun create vue` the generated readme contains the following instructions to run `bun build` in order to compile and minify the project.

    ### Compile and Minify for Production
    
    ```sh
    bun build
    ```

But trying to run this gives a confusing error message

```
> bun build
bun build v1.1.34 (5e5e7c60)
error: Missing entrypoints. What would you like to bundle?

Usage:
  $ bun build <entrypoint> [...<entrypoints>] [...flags]

To see full documentation:
  $ bun build --help
```

This doesn't work because [Bun has a built-in `build` command](https://bun.sh/docs/bundler) which gets executed instead of the `build` script defined in package.json.

### Expected behavior

The generated readme uses `bun run build` instead, as this will run the build script instead of the built-in bun bundler.

### How to reproduce

1. Run `bun create vue`
2. Accept all defaults
3. Observe that vue-project/README.md mentions using `bun build` instead of `bun run build`
4. Observe that running `bun build` gives an error message instead of invoking the build script.

**Comment by cexbrayat** [comment]
Hi @Hornwitser 

👍 Can you open a PR to fix this? We will gladly review and merge it!

The readme generator is in https://github.com/vuejs/create-vue/blob/9201bdb46e5c13126e363a33281787f2204a3ac0/utils/generateReadme.ts#L11 I think there are no unit tests for this function, but you can add some in `__test__` if you're up to it.

**Comment by Hornwitser** [comment]
By fixing this, do you mean adding `run` between `${packageManager}` and `${scriptName}` here?

https://github.com/vuejs/create-vue/blob/9201bdb46e5c13126e363a33281787f2204a3ac0/utils/getCommand.ts#L9-L11

What I will say is that while shortcuts like `pnpm build` or just `yarn` are nice, they make it more difficult for new developers to understand what's going on and find the relevant documentation. They also run the risk of the package managers adding new commands that clash with them.

**Comment by cexbrayat** [comment]
I don't think we want to add it for every command, you can just add it for `bun build`, like:

```ts
if (scriptName === 'build') {
    return packageManager === 'bun' ? 'bun run build' : `${packageManager} build`
  }
```
