### ISSUE TITLE
can not use `[].at` at project

### ISSUE THREAD

**Issue by zhangenming** [vuejs/create-vue#620]
![image](https://github.com/user-attachments/assets/b3622320-e918-49ff-adaa-c2e1e1662672)

**Comment by lean-dev** [comment]
Hi, this is no bug.

As stated in the comment:

> Support for newer versions of language built-ins are left for the users to include

Add the following line in your `tsconfig.app.json` in the `compilerOptions` (e.g. at line 8):

`"lib": ["ES2023", "DOM", "DOM.Iterable"],`

At least ES2022 must be chosen.
