### ISSUE TITLE
'vite-plugin-vue-devtools' problem

### ISSUE THREAD

**Issue by artemklishch** [vuejs/create-vue#633]
### Error with "vite-plugin-vue-devtools"

When I create the default project with the command "npm create vue@latest" and the run "npm run dev" i get the error:
failed to load config from ....<project_name>/vite.config.ts
error when starting dev server:
Error: Cannot find module '...<project_name>/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'

### Additional context
My "vite.config.ts" file with default content is:
`import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import vueDevTools from 'vite-plugin-vue-devtools'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    vueJsx(),
   vueDevTools(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
})
`
And when i remove/comment the line with the "vueDevTools()" plugin - there is no that error. It it possibli to work, but I assume that I can need that at some point of time. And it would be nice to figure out how to fix it.

I tried to use 18.... version of the NodeJS, but it wasn't helpful.

Thank you for any help.

**Comment by haoqunjiang** [comment]
Let's track this issue in https://github.com/vuejs/create-vue/issues/634

**Comment by artemklishch** [comment]
Thank you so much!

вт, 10 дек. 2024 г. в 10:20, Haoqun Jiang ***@***.***>:
