### ISSUE TITLE
Error when building with `npm build`, related to @jridgewell/genmapping sub-dependency

### ISSUE THREAD

**Issue by dennybiasiolli** [vuejs/create-vue#634]
When building a freshly created project, this error appears

```
Error: Cannot find module '/Users/denny/git/budgest-frontend/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'
```

Related to this issue: https://github.com/jridgewell/gen-mapping/issues/14
A possible workaround is to install a fixed 0.3.5 version of the dependency with

`npm install -D @jridgewell/gen-mapping@0.3.5`

**Comment by the-pawn-2017** [comment]
think you, bro!

**Comment by artemklishch** [comment]
Thank you!
