### ISSUE TITLE
The latest version of create vue creates projects with built-in developer tools.

### ISSUE THREAD

**Issue by y3342113181** [vuejs/create-vue#649]
The latest version of create vue creates projects with built-in developer tools. Can there be an option for developers to choose?

**Comment by cexbrayat** [comment]
Assuming you're talking about the devtools, it used to be an option but the team chose to enable them by default (see https://github.com/vuejs/create-vue/pull/602). It's fairly easy to remove them from a created project if you don't want to use them 👍

**Comment by haoqunjiang** [comment]
You can disable the floating panel in settings:
![image](https://github.com/user-attachments/assets/8bade912-78d1-4214-b035-9dfbe543cf36)

The Vite plugin does more than a floating interface - there are features in the new devtools that are only available with it:
https://devtools.vuejs.org/getting-started/features#assets-vite-only

**Comment by y3342113181** [comment]
For vue devtools, integrating it into the create vue build tool actually affects the use of the vue devtools browser plugin. I am not aware of whether the new features of the new version of vue devtools will be applied in the browser plugin.

**Comment by y3342113181** [comment]
In addition, the vue devtools browser plugin has not been updated for a long time, and even the Chrome plugin version on the vue devtools official website is 6.6.4, the edge plugin version is 6.6.3, and even the redirect link for the edge plugin is the address of the Chrome plugin store.

**Comment by haoqunjiang** [comment]
The latest version is 7.6.8 https://chromewebstore.google.com/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?utm_source=ext_sidebar&pli=1
If you see 6.6.4, you might be using the wrong plugin (the legacy one: https://chromewebstore.google.com/detail/vuejs-devtools/iaajmlceplecbljialhhkmedjlpdblhp?hl=en)

**Comment by y3342113181** [comment]
So why keep the old version plugins, and the edge plugin store doesn't have the latest vue devtools plugin

**Comment by haoqunjiang** [comment]
> So why keep the old version plugins

The new version does not support Vue 2. The legacy version is there for those developing legacy Vue 2 projects.

> and the edge plugin store doesn't have the latest vue devtools plugin

Thanks for the info. I’ll sync with the team about this situation.

**Comment by y3342113181** [comment]
You can clearly indicate in the plugin store that it is suitable for Vue2 or Vue3. Additionally, you did not answer the question about the Vue devtools official website and the edge plugin redirect address to the Chrome plugin store.
![image](https://github.com/user-attachments/assets/536497f9-9ba2-445a-952d-0cfb0da016da)

**Comment by haoqunjiang** [comment]
I’m not part of the devtools team so all I can do is to pass along your concerns to them.

**Comment by y3342113181** [comment]
Okay, could you please convey the issue
