### ISSUE TITLE
prettier-plugin-tailwindcss is not working with create-vue

### ISSUE THREAD

**Issue by Bosphoramus** [vuejs/create-vue#67]
The plugin "[prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)" is supposed to work when you install it with no more setup needed, but in create-vue projects it doesnt work. Supposedly it should sort your tailwindcss on format (with prettier) but it just doesnt, no errors, nothing.

Using VSCode

**Comment by sodatea** [comment]
I guess it's fixed since https://github.com/tailwindlabs/prettier-plugin-tailwindcss/releases/tag/v0.1.8

If the issue persists, please open a new issue with a reproduction. Thanks!
