### ISSUE TITLE
Error: EPERM: operation not permitted, mkdir 'C:\Users\Philip'

### ISSUE THREAD

**Issue by TradeIdeasPhilip** [vuejs/create-vue#77]
I'm new to Vue.  I'm copying directly from [the Vue tutorial](https://vuejs.org/guide/quick-start.html#with-build-tools).

```
Philip Smolen@DESKTOP-UOBK4AV MINGW64 /c/simple-projects/vue-test
$ npm init vue@latest
Error: EPERM: operation not permitted, mkdir 'C:\Users\Philip'
command not found: create-vue

Philip Smolen@DESKTOP-UOBK4AV MINGW64 /c/simple-projects/vue-test
$
```

It looks like a script is choking because my home directory has a space in it.

I tried several variations on this theme with no success.  I tired it under Git Bash and Windows Power Shell.  I moved to a directory without any spaces in the name.  I tried `vue@3` as recommended on [another page](https://github.com/vuejs/create-vue).  I tried --verbose but it didn't show anything useful.

Please advise.  How do I get started with Vue?  Thanks!

**Comment by TradeIdeasPhilip** [comment]
Never mind.  I reinstalled node and npm and now I'm past that error.

**Comment by sodatea** [comment]
If anyone encounters this error too, here's a reference to the `npx` bug: https://github.com/zkat/npx/issues/146#issuecomment-384016791
