### ISSUE TITLE
Bug when we add Vue Router by default. 

### ISSUE THREAD

**Issue by Vallejoanderson** [vuejs/create-vue#85]
A bug appears when we select the Vue Router option after `npm init vue@latest`. Given the bug I had to unselected it and installed Vue Router manually and everything ok at that point.  Anyway, I thought it was a good idea to report this issue. The errors and the steps I took are shown below.

![image](https://user-images.githubusercontent.com/48649209/162882443-683ca0be-d372-4ba9-9584-46869acf8950.png)
![image](https://user-images.githubusercontent.com/48649209/162882754-a0531cca-1f94-4124-ba32-b9ba51840da6.png)

**Comment by chocotree** [comment]
Check this.
[esbuild0.14.35 is not compate with vite](https://github.com/vitejs/vite/issues/7683)

And the bug is Fixed in esbuild 0.14.36.
