### ISSUE TITLE
Adding preset support

### ISSUE THREAD

**Issue by laoshaw** [vuejs/create-vue#88]
so we can automate vue3 project creation

**Comment by sodatea** [comment]
I'm not going to add this feature. Too much complexity.

For simple projects, the command line arguments should suffice: https://github.com/vuejs/create-vue/blob/f280b26fe938080967c332d88fa6eaba70dab870/index.ts#L72-L85
If you need more customization, please create your own scaffold, like https://github.com/vuetifyjs/create-vuetify
