### ISSUE TITLE
Very old vue-tsc version

### ISSUE THREAD

**Issue by sethidden** [vuejs/create-vue#9]
The vue-tsc version in this repo is 0.3.0, newest is 0.28.x

Scenario where this matters:
1. Someone creates a project using create-vue
2. He wants to remake the default template from SPA to component library to publish on NPM
3. He changes the "build" script in NPM to [vue-tsc --declaration --emitDeclarationOnly](https://github.com/johnsoncodehk/volar/blob/master/packages/vue-tsc/README.md?plain=1#L24) && vite build, so that the lib contains rich typings for the components
4. He gets the 
```
/home/user/vue-tsc-component-library-example/node_modules/vue-tsc/proxy.js:8
        throw 'emit mode is not yet support';
```
error.

The fix for the above error is to just run `npm i -D vue-tsc@latest` after `npm init vue@next`, but it'd be nice if the project shipped with the new version

**Comment by sodatea** [comment]
Fixed in beta.7
