### ISSUE TITLE
Whether eslint and prettier add a single quote support

### ISSUE THREAD

**Issue by qcyblm** [vuejs/create-vue#93]
![image](https://user-images.githubusercontent.com/64412486/165669888-cf056e51-7681-45ab-82c1-575b2fb56c29.png)

**Comment by nickmccurdy** [comment]
Single and double quotes are supported in the JS/ES spec. This doesn't have anything to do with Vue, Create Vue, Vite, ESLint, or Prettier.

**Comment by segevfiner** [comment]
It's prettiers default config to prefer double quotes. It can be configured but this project doesn't do that ATM.

**Comment by Eunknight** [comment]
Please refer to
https://github.com/vuejs/core/blob/main/.prettierrc#L2

prettier options
https://prettier.io/docs/en/options.html
prettier Configuration File
https://prettier.io/docs/en/configuration.html

**Comment by segevfiner** [comment]
We might want to include this in the template should the generated code keep following this style, to avoid formatting errors. Although it is kind of opinionated.

**Comment by qcyblm** [comment]
> Please refer to https://github.com/vuejs/core/blob/main/.prettierrc#L2 https://github.com/vuejs/create-vue/blob/main/.prettierrc#L4
> 
> prettier options https://prettier.io/docs/en/options.html prettier Configuration File https://prettier.io/docs/en/configuration.html
> 
> my config `.prettierrc.yaml`
> 
> ```
> semi: false
> singleQuote: true
> endOfLine: auto
> ```

This can be solved by adding a Prettier configuration file to the root of the Vue project, which you want to include when you create a Vue project and select Prettier

`.prettierrc`
```
{
  "singleQuote": true,
  "semi": false,
  "trailingComma": "none"
}
```
