### ISSUE TITLE
.vscode/extensions.json references old publisher johnsoncodehk instead of vue

### ISSUE THREAD

**Issue by segevfiner** [vuejs/create-vue#97]
It seems that the Volar and TypeScript Vue Plugin have moved to the `vue` publisher ID in the VS Code marketplace where they previously were `johnsoncodehk`. They still are `johnsoncodehk` in the `package.json` of the version that currently gets installed (Guess they weren't released since the rename), but that no longer works in `extensions.json` to recommend them and it should now be:
```
"vue.volar", "vue.vscode-typescript-vue-plugin"
```

**Comment by segevfiner** [comment]
I think https://github.com/vuejs/create-vue/pull/95, fixes this.

**Comment by sodatea** [comment]
Fixed.
